### ISSUE TITLE
Make it works with lovelace-auto-entities

### ISSUE THREAD

**Issue by oncleben31** [benct/lovelace-multiple-entity-row#1]
Is it possible to make it work with https://github.com/thomasloven/lovelace-auto-entities
using templating like works https://github.com/custom-cards/secondaryinfo-entity-row ?

**Comment by benct** [comment]
I've had a look at the auto-entities component and I cannot quite see what makes in incompatible. I don't use that card myself, so I haven't had the chance to try it out though. Are your sure it doesn't work with something like the following config?
```
type: custom:auto-entities
card:
  type: entities
entities:
  - type: custom:multiple-entity-row
    entity: <your entity>
filter:
  ...
```

If so, what is wrong? Are the any errors in the browser console?

**Comment by oncleben31** [comment]
I've a working example with a similar card:
```
card:
  show_header_toggle: false
  title: Batteries faibles
  type: entities
filter:
  exclude:
    - domain: vacuum
    - entity_id: '*pressure*'
    - entity_id: '*humidity*'
  include:
    - attributes:
        battery_level: <= 30
      options:
        secondary_info: 'Battery: [[ {entity}.attributes.battery_level ]]'
        type: 'custom:secondaryinfo-entity-row'
show_empty: true
type: 'custom:auto-entities'
```

I've tried to do something similar with yours and the addition of attribute is ignored:
```
card:
  show_header_toggle: false
  title: Batteries faibles
  type: entities
filter:
  exclude:
    - domain: vacuum
    - entity_id: '*pressure*'
    - entity_id: '*humidity*'
  include:
    - attributes:
        battery_level: <= 30
      options:
        type: custom:multiple-entity-row
        primary:
          entity: '[[ {entity} ]]'
          attribute: battery_level
          name: Battery
          unit: '%'
show_empty: true
type: 'custom:auto-entities'
```
I did not see any error message. Perhaps you should add something to support the generic tag `[[ {entity} ]]` ?

**Comment by benct** [comment]
I'm not too sure how to implement support for this just now and I don't have too much spare time atm, but I will try to look more into this when possible. If anyone would like to contribute towards this and submit a PR, I'd appreciate it.

**Comment by crowbarz** [comment]
secondaryinfo-entity-row directly supports using card-tools/parseTemplates in the secondary_info option. The templates are not actually rendered by auto-entities, looking at the code and playing around with some test configs it seems to just applies the options maps verbatim to the generated list of entities.

In fact secondaryinfo-entity-row _only_ supports templates on the secondary_info option. Try this filter:
```
filter:
   include:
    - <some_filter>
      options:
        type: 'custom:secondaryinfo-entity-row'
        name: '[[ {entity} ]]'
        secondary_info: '[[ {entity} ]]'
```
The entity's friendly_name is overridden by the name option and displays literally as '[[ {entity} ]]', whereas the secondary_info shows up as the entity id resulting from the rendered template. That demonstrates that auto-entities is not rendering any templates.

Looks like template rendering support in auto-entities has been requested [here](https://github.com/thomasloven/lovelace-auto-entities/issues/28) already. IMHO it probably makes more sense to render templates in filter/conditional cards like auto-entities that generates a dynamic list of entities, rather than implementing some kind of templating in virtually every card in HA.
