### ISSUE TITLE
Allow `last-changed` in entities

### ISSUE THREAD

**Issue by cadavre** [benct/lovelace-multiple-entity-row#101]
Currently we can easily set `last-changed` as `secondary_info`, but we cannot set `last_changed` parameter in entities list.

```yaml
    entities:
      - type: 'custom:multiple-entity-row'
        entity: binary_sensor.0x00158d00034d6c68_contact
        entities:
          - attribute: last_changed
```

Because there's not such attribute, `last_changed` is entity state attribute.

Feature request: add possibility to access entity state attributes, like last_changed and last_updated.

---

EDIT:

It could also be solved with #35 but I can see points in that issue.

For this case imagine using "motion sensor" as an entity which can display info like this:

```
[ ] Office windows           [opened] [8 minutes ago]
    ^ entity name             ^ state  ^ last-changed
```

Would be so nice to read!
