### ISSUE TITLE
Icon + Entity_state showed at the same time

### ISSUE THREAD

**Issue by joselcaguilar** [benct/lovelace-multiple-entity-row#105]
Hi @benct, thx for this module, it is awesome!

I cannot see the option to use an icon instead of name title for entities, if we are using an icon, HA expects a tap_action instead of entity_state and I'd would like to use the icon as a "name" and then a little bit down the entity_state (-32 dBm in this example), I mean something like this:
![image](https://user-images.githubusercontent.com/7523585/95080338-46996680-0718-11eb-9868-fdff5fcb508f.png)
```
entities:
  - entity: sensor.cepillo_dientes_rssi
    name: false
    icon: true
    show_state: true
```
Could be added or is there a workaround to achieve this?
Thx in advance!
