### ISSUE TITLE
tap action navigate doesn't work

### ISSUE THREAD

**Issue by smhgit** [benct/lovelace-multiple-entity-row#107]
I have upgraded to the latest version and added tap action navigate. It doesn't seems to work. Can you please add an example so I can make sure I added it properly?

**Comment by benct** [comment]
Something like this?
```
action: navigate
navigation_path: '/lovelace/0'
```

**Comment by smhgit** [comment]
This is what I have but it doesn't work:

```
          - entity: sensor.read_your_meter
            type: custom:multiple-entity-row
            name: Water Meter
            show_state: false
            secondary_info: last-changed
            tap_action:
              action: navigate
              navigation_path: /lovelace/2
            entities:
```
