### ISSUE TITLE
0.116 State Color Not Happening

### ISSUE THREAD

**Issue by woodmj74** [benct/lovelace-multiple-entity-row#108]
Hi, just upgraded to 0.116 and the state color appears to have stopped working, example card:

```
  - entities:
      - entity: binary_sensor.lounge_low_light
        type: 'custom:multiple-entity-row'
        secondary_info: last-changed
        show_state: false
        entities:
          - entity: sensor.lounge_light_level
            name: Current
      - entity: binary_sensor.landing_low_light
        secondary_info: last-changed
    state_color: true
    type: entities
```

In this case, the binary_sensor.landing_low_light will light up when on (i.e. the icon turns yellow) but the binary_sensor.lounge_low_light won't when on. Removing the type: 'custom:multiple-entity-row' config from it then returns to expected behavior.

I believe this was functional prior to 0.116

![image](https://user-images.githubusercontent.com/68328701/95438948-e4767680-094e-11eb-8532-f9d59fc22987.png)
