### ISSUE TITLE
Expected a value of type ...  but received ...

### ISSUE THREAD

**Issue by genem2** [benct/lovelace-multiple-entity-row#11]
I'm suspecting this might be rooted in the [ha-wyzesense](https://github.com/kevinvincent/ha-wyzesense) component, but:

Adding this Lovelace card:

```
type: entities
entities:
  - entity: binary_sensor.outer_front_door
    primary:
      attribute: battery_level
      entity: binary_sensor.outer_front_door
      name: Battery
      unit: '%'
    secondary:
      attribute: rssi
      entity: binary_sensor.outer_front_door
      name: Wi-Fi
    type: 'custom:multiple-entity-row'
show_header_toggle: false

```
The card appears to render fine, but below the editor window, we have:

```
Expected a value of type `{entity,name,icon} | entity-id` 
for `entities.0.primary` 
but received `{"attribute":"battery_level","entity":"binary_sensor.outer_front_door","name":"Battery","unit":"%"}`.
```

Maybe that component isn't returning something you're expecting as standard?

For my sensor's states:

```
binary_sensor.outer_front_door
{
  "assumed_state": true,
  "battery_level": 93,
  "device_class": "door",
  "friendly_name": "Outer front door",
  "mac": "7788E675",
  "rssi": -62,
  "timestamp": "2019-09-22T08:28:51.400000"
}
```

Appreciate your thoughts.
