### ISSUE TITLE
Custom alignment for "name" for additional states

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#111]
"Additional states" - means states specified in inside the "entities" section:
```
  - type: 'custom:multiple-entity-row'
    entity: SOME_ENTITY_ID
    entities:
      - entity: SOME_ADDITIONAL_ENTITY_ID_1   # this one
        name: 'some name 1'
      - entity: SOME_ADDITIONAL_ENTITY_ID_2   # and this one
        name: 'some name 2'
```
Currently this names are aligned "center".
There would be great to have a possibility to customize it like:
```
  - type: 'custom:multiple-entity-row'
    entity: SOME_ENTITY_ID
    entities:
      - entity: SOME_ADDITIONAL_ENTITY_ID_1
        name: 'some name 1'
        align_name: left
      - entity: SOME_ADDITIONAL_ENTITY_ID_2
        name: 'some name 2'
        align_name: center
```
Also, there would be great to customize alignment for the values:
```
  - type: 'custom:multiple-entity-row'
    entity: SOME_ENTITY_ID
    entities:
      - entity: SOME_ADDITIONAL_ENTITY_ID_1
        align: left
      - entity: SOME_ADDITIONAL_ENTITY_ID_2
        align: center
```
Currently the values are aligned (if I am right):
- string values are aligned "right";
- numerical values are aligned "center".
