### ISSUE TITLE
Specify a "width" for every additional state

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#112]
"Additional states" - means states specified in inside the "entities" section:
```
  - type: 'custom:multiple-entity-row'
    entity: SOME_ENTITY_ID
    entities:
      - entity: SOME_ADDITIONAL_ENTITY_ID_1   # this one
        name: 'some name 1'
      - entity: SOME_ADDITIONAL_ENTITY_ID_2   # and this one
        name: 'some name 2'
```
In case of several similar rows it may not look perfect:
![1](https://user-images.githubusercontent.com/71872483/95685108-87085100-0bfe-11eb-8445-65113ff7841b.jpg)
Here for some row a battery level is <10% and the corresponding string value has a smaller width.
That is why the "table" became not "perfect" since some values are shifted horizontally.

Currently I have to "widen" names like this:
name: '- level -'
As a result the table becomes more nice since all values are aligned better:
![2](https://user-images.githubusercontent.com/71872483/95685199-17469600-0bff-11eb-834c-0902cdd10851.jpg)

But on iPhone again I can see misalignment - may be because of limited possibilities of my method.

So, it would be great to have some possibility to specify a width somehow for every parameter.
Actually, I do not know how to do it. In my practice I used "tabs" (\t) for aligning values in tables.
