### ISSUE TITLE
Status Color is not working properly

### ISSUE THREAD

**Issue by Merwenus** [benct/lovelace-multiple-entity-row#116]
I don't know when the problem started, but I'm sure a couple of HA versions before (probably the previous 0.115 worked good) it showed motion sensor with proper status color.

Both motion sensors are active and shows motion but the one with 'multiple-entity-rows' icon color is in inactive state with HA 0.116.4 and todays 3.5.0 multiple entity row addon in HACS.
https://i.imgur.com/RHnHolp.png

The configuration for this 2 identical binary_sensor.motion_sensor_xxx
```
      - binary_sensor.motion_sensor_158d0001ad3fxx
      - entity: binary_sensor.motion_sensor_158d00016c30yy
        type: custom:multiple-entity-row
        secondary_info: last-changed
        entities:
        - entity: sensor.illumination_158d00016c30b7
          name: false
```
