### ISSUE TITLE
Hide an entity if attribute is unavailable or not found

### ISSUE THREAD

**Issue by NicoSomerwil** [benct/lovelace-multiple-entity-row#119]
Thanks for your great card. Love it!

I'm struggling getting the option: 'hide_unavailable: true' working.

I must be doing something wrong, so, please, do you have an example/hint for me?

Please take a look [here](https://community.home-assistant.io/t/lovelace-multiple-entity-row/109109/84?u=nicos) for the used code.

Thanks in advance for looking at this 'issue'. 

Good luck and success with your very useful card, thanks!!

**Comment by ericvitale** [comment]
I'm also having this issue with the latest version (v3.5.1) of the component.

```
- entity: light.master_bathroom_shower_lights
type: custom:multiple-entity-row
name: Shower
secondary_info: last-changed
toggle: true
icon: mdi:shower-head
entities:
  - attribute: brightness
     unit: '%'
     hide_unavailable: true
```
