### ISSUE TITLE
Confirmation not working for service

### ISSUE THREAD

**Issue by smhgit** [benct/lovelace-multiple-entity-row#121]
In the following case, the confirmation doesn't work, any idea why? (I have other cases which work)

```
          - type: vertical-stack
            cards:
              - type: entities
                show_header_toggle: false
                entities:
                  - type: custom:multiple-entity-row
                    entity: sun.sun
                    icon: mdi:server
                    name: Server control
                    show_state: false
                    entities:
                      - icon: mdi:restart
                        tap_action:
                          action: call-service
                          service: homeassistant.restart
                        confirmation: 'Restart home assistant?'
```
