### ISSUE TITLE
Support brightness option for formatting

### ISSUE THREAD

**Issue by benct** [benct/lovelace-multiple-entity-row#128]
Please add support brightness option for formatting. At version 4.0.0 you add brightness support to secondary_info but in some cases more useful to have it as separate entity, for example (in my case brightness attribute it's a value from 0-255) :
```
type: 'custom:auto-entities'
card:
  type: entities
filter:
  exclude:
    - state: 'off'
  include:
    - domain: light
      attributes:
        supported_features: 1
      options:
        type: 'custom:multiple-entity-row'
        secondary_info: last-changed
        state_color: false
        toggle: true
        entities:
          - attribute: brightness
            name: false
            format: !!!brightness option will be great!!!
```

_Originally posted by @myhomeiot in https://github.com/benct/lovelace-multiple-entity-row/issues/127#issuecomment-721816055_
