### ISSUE TITLE
more-info tap action is broken on 4.0.0

### ISSUE THREAD

**Issue by SaifAqqad** [benct/lovelace-multiple-entity-row#129]
Setting the tap action of an entity to `more-info` for another entity is broken on 4.0.0, I downgraded to 3.5.1 and it works perfectly

```yaml
type: entities
entities:
  - entity: sensor.motion_garage
    name: Outdoor garage
    secondary_info:
      attribute: event_time
      format: relative
    tap_action:
      acton: more-info
      entity: camera.motion_garage
    type: 'custom:multiple-entity-row'

```
