### ISSUE TITLE
Object Name false not working v4.0.0

### ISSUE THREAD

**Issue by bgrr74** [benct/lovelace-multiple-entity-row#131]
Hi

After updating to V4.0.0 i noticed that name: false is no longer working to hide the name. 
Changing the name is working but setting it to false does not work anymore.

I switched back to v3.5.1 and name: false is working again
```
entities:
  - entities:
      - entity: light.woonkamer_eettafel
      - entity: light.woonkamer_leeslamp
    entity: light.woonkamer_leeslamp
    icon: 'mdi:home'
    name: false
    show_state: false
    type: 'custom:multiple-entity-row'
type: entities
```

![screenshot](https://user-images.githubusercontent.com/48893544/98294014-88cff500-1faf-11eb-95f9-f3c367b72ca3.png)
