### ISSUE TITLE
Support "reverse-position" option for formatting and secondary_info

### ISSUE THREAD

**Issue by myhomeiot** [benct/lovelace-multiple-entity-row#135]
In home assistant [cover position](https://www.home-assistant.io/integrations/cover) it's a value from 0 to 100 which shows how much cover/blind/awning **is open**, for example 100 mean fully open. For many users this representation it's not native and they prefer to see how much cover **is closed**, for example 0 for fully open and 100 for fully close. In order to do it we need to make sensor for every cover which will subtract current position from 100:
```
    cover_living_room_current_position:
      friendly_name: Cover Living Room Current Position
      unit_of_measurement: '%'
      icon_template: 'mdi:blinds'
      value_template: "{{ 100 - state_attr('cover.living_room', 'current_position') }}"
```

It's will be very useful to have this **reverse-position** option for formatting and secondary_info which will do this calculation (100 - current_position).

Update: HA [secondary_info](https://www.home-assistant.io/lovelace/entities/#secondary_info) also support the `tilt-position` but I'm not sure if it's required reverse equivalent probably, it's will be good to have for consistency.
