### ISSUE TITLE
hide_unavailable for secondary_info

### ISSUE THREAD

**Issue by myhomeiot** [benct/lovelace-multiple-entity-row#136]
If it's possible, please support `hide_unavailable` for secondary_info
```
  type: 'custom:multiple-entity-row'
  entity: climate.office
  secondary_info:
    entity: climate.office_2
    attribute: hvac_action
    name: 'Action: '
    hide_unavailable: true
```
