### ISSUE TITLE
Unit not being shown in secondary_info

### ISSUE THREAD

**Issue by McGiverGim** [benct/lovelace-multiple-entity-row#138]
I have a card with several multiple-entity-row. Is an energy graph, and in the secondary info It showed the cost of the energy. This worked until some version, but I have observed that now the unit of this cost (€ euro symbol) is not being shown.

This is the card (the symbol must go in the red dots):
![image](https://user-images.githubusercontent.com/2673520/98642881-726ac600-232e-11eb-9365-015e114246f6.png)

And this is the yaml:
```yaml
cards:
  - entities:
      - entities:
          - aggregate_func: max
            entity: sensor.energia_diaria
            name: Consumo diario
          - aggregate_func: max
            entity: sensor.energia_coste_diario
            name: Coste diario
            y_axis: secondary
        group_by: date
        hour24: true
        hours_to_show: 168
        show:
          graph: bar
          icon: false
          name: true
          state: true
        show_state: false
        type: 'custom:mini-graph-card'
    show_header_toggle: false
    title: Resumen 7 días
    type: entities
  - entities:
      - entities:
          - entity: utility_meter.energia_diaria
            name: Tarifa
          - entity: sensor.energia_diaria_pico
            name: Pico
          - entity: sensor.energia_diaria_valle
            name: Valle
        entity: sensor.energia_diaria
        icon: 'mdi:calendar'
        name: Hoy
        secondary_info:
          entity: sensor.energia_coste_diario
          name: null
        type: 'custom:multiple-entity-row'
      - entities:
          - entity: sensor.energia_semanal_pico
            name: Pico
          - entity: sensor.energia_semanal_valle
            name: Valle
        entity: sensor.energia_semanal
        icon: 'mdi:calendar'
        name: Esta semana
        secondary_info:
          entity: sensor.energia_coste_semanal
          name: null
        type: 'custom:multiple-entity-row'
      - entities:
          - entity: sensor.energia_mensual_pico
            name: Pico
          - entity: sensor.energia_mensual_valle
            name: Valle
        entity: sensor.energia_mensual
        icon: 'mdi:calendar'
        name: Este mes
        secondary_info:
          entity: sensor.energia_coste_mensual
          name: null
        type: 'custom:multiple-entity-row'
      - entities:
          - entity: sensor.energia_anual_pico
            name: Pico
          - entity: sensor.energia_anual_valle
            name: Valle
        entity: sensor.energia_anual
        icon: 'mdi:calendar'
        name: Este año
        secondary_info:
          entity: sensor.energia_coste_anual
          name: null
        type: 'custom:multiple-entity-row'
    show_header_toggle: false
    title: Consumo agrupado
    type: entities
in_card: true
type: vertical-stack
```

The sensor contains the unit in his info, for example:
![image](https://user-images.githubusercontent.com/2673520/98642972-99c19300-232e-11eb-812f-59ef212db8f2.png)

But I have tried to add it too manually (`unit: '€'` in the `secondary-info`) without luck

Some idea of what is wrong? As I say it was working in some earlier version, I don't know when this was broken.

Thanks!

**Comment by McGiverGim** [comment]
I forgot to say that I'm on the latest version, 4.0. I have seen this similar issue: https://github.com/benct/lovelace-multiple-entity-row/issues/117 but as far as I know, the fix must be included in the 4.0 version.

**Comment by benct** [comment]
Hmm, very strange.. this should work, both with and without specifying `unit` manually..

**Comment by McGiverGim** [comment]
Yes, and I have reboot the system several times since the problem start.
Today I have upgraded to version 4.1 and the problem continues.

**Comment by McGiverGim** [comment]
I have reproduced it with the minimum possible card:

![image](https://user-images.githubusercontent.com/2673520/99046254-cbd32f00-2592-11eb-8d2c-fdbb691862d5.png)

```yaml
entities:
  - entities:
    entity: sensor.energia_diaria
    secondary_info:
      entity: sensor.energia_coste_diario
      name: null
    type: 'custom:multiple-entity-row'
type: entities
```

It does not matter if I add `unit: €` or not.

The sensor has been created by a utility meter, I don't think this matters:
```yaml
utility_meter:
  energia_coste_diario:
    source: sensor.energia_coste_horario
    cycle: daily
    tariffs:
      - pico
      - valle
```

![image](https://user-images.githubusercontent.com/2673520/99047133-06899700-2594-11eb-977c-6914b10ca43a.png)
![image](https://user-images.githubusercontent.com/2673520/99047495-92032800-2594-11eb-9545-7f9684f42863.png)

I'm a developer but I don't know nothing about python. But maybe can help if I add/remove something directly in the file?

**Comment by McGiverGim** [comment]
I've observed this is not the only attribute ignored in the `secondary-info`. In other card, the `format` is ignored too. But maybe in this case is caused by the data not being correct (the `timestamp` maybe has not correct format).

For example this:
```yaml
entities:
  - entity: binary_sensor.snapshots_stale
    name: Estado
    secondary_info:
      attribute: last_snapshot
      entity: sensor.snapshot_backup
      format: relative
      name: Última copia
    type: 'custom:multiple-entity-row'
show_header_toggle: false
title: Copias de seguridad
type: entities
```
Must show the date as relative, but it shows:
![image](https://user-images.githubusercontent.com/2673520/99065228-59207e80-25a7-11eb-9e4f-c0a87c25fbff.png)

This is the sensor:
![image](https://user-images.githubusercontent.com/2673520/99065359-9258ee80-25a7-11eb-94d1-f2eb92aa1b8c.png)
