### ISSUE TITLE
Action object configuration change (eg. confirmation text no longer displayed)

### ISSUE THREAD

**Issue by crowbarz** [benct/lovelace-multiple-entity-row#139]
The way to configure actions seems to have changed in 4.0.0, possibly as the code now seems to use [`custom-card-helpers/handleClick()`](https://github.com/custom-cards/custom-card-helpers/blob/master/src/handle-click.ts) to parse action objects.

I discovered this after noticing that custom confirmation text in `tap_action` specified as a string no longer worked, as in `handleClick()` the `confirmation` property is an object rather than boolean/string, meaning that the confirmation text needs now to be specified like this:

```yaml
tap_action:
  action: call-service
  confirmation:
    text: Confirm?
  service: script.restart_service_from_sensor
```

Should the Actions object documentation be replaced with a link to the [Lovelace documentation on actions](https://www.home-assistant.io/lovelace/actions/)? If so, then I can raise a PR to update `README.md` accordingly. It looks to me that they were broadly the same (apart from the way `confirmation` was handled) but I may be missing semantics.
