### ISSUE TITLE
Multiple entity row isn't displaying correctly?

### ISSUE THREAD

**Issue by pejotigrek** [benct/lovelace-multiple-entity-row#14]
I'm not sure if it's a bug or feature, but something is off I guess.
multiple row displays correct values, but design of the row is different than other elements.

Example:
![temp_screen](https://user-images.githubusercontent.com/10796588/66262160-b0b4be00-e7db-11e9-8438-2ef4e5d34094.jpg)

I'd love to see multiple row in the same style as the rest - is there something I can do? or maybe it's just my lovelace behaving odd? I didn't "turned off" the styles so it supposed to display correctly, right?

**Comment by benct** [comment]
Have you put it inside an entities card? This **row**-card requires to be put inside an entities card, as it renders as one row in that card.

```
type: entities
entities:
  - entity: <your entity>
    type: custom:multiple-entity-row
```
