### ISSUE TITLE
On 4.1.0, states/attributes that are string formatted dates are not being formatted at all

### ISSUE THREAD

**Issue by SaifAqqad** [benct/lovelace-multiple-entity-row#142]
So basically, if an entity's state or attribute is a string formatted date like: `2020-11-13 17:38:33`, and I use `format: relative` or any other format type, that string is just returned as is instead of making a new Date object with it.

I think it has to do with [this line](https://github.com/benct/lovelace-multiple-entity-row/blob/c20aa7d5d40fa53d2dcc2b3785e462e98c3c58ba/src/index.js#L135)

**Comment by ildar170975** [comment]
I have to confirm the problem.
On my setup:

```
        secondary_info:
          entity: device_tracker.life360_somebody
          name: false
          attribute: last_seen
          format: relative
```
Now it looks like this:
![изображение](https://user-images.githubusercontent.com/71872483/99093359-69564f00-25e3-11eb-90a8-f151d252c10c.png)
