### ISSUE TITLE
Last-updated doesn't appear to work.

### ISSUE THREAD

**Issue by bremor** [benct/lovelace-multiple-entity-row#144]
Thanks for this great lovelace card! I am having a small issue with the `last-updated` secondary attribute. When I set `secondary_info `as `last-updated`, it does not show in the card.

```
type: entities
entities:
  - entity: switch.dishwasher_switch
    type: 'custom:multiple-entity-row'
    name: Diswasher
    show_state: false
    secondary_info: last-changed
    entities:
      - attribute: linkquality
        name: Link Quality
  - entity: switch.dishwasher_switch
    type: 'custom:multiple-entity-row'
    name: Diswasher
    show_state: false
    secondary_info: last-updated
    entities:
      - attribute: linkquality
        name: Link Quality
```
![image](https://user-images.githubusercontent.com/34525505/99465424-834eb380-298e-11eb-8b6e-7736cc07e792.png)
