### ISSUE TITLE
'format:' and 'unit: false' doesn't work correctly

### ISSUE THREAD

**Issue by geradtl** [benct/lovelace-multiple-entity-row#145]
Hello. If I use at same time **format** and **unit** property for entity object, **unit: false** doesn't work correctly. Cards don't hide units info.

```
entities:
  - entity: sensor.temperature
    name: Current
    unit: false
    format: precision1
```
