### ISSUE TITLE
Comma separated thousands separator

### ISSUE THREAD

**Issue by bigmak40** [benct/lovelace-multiple-entity-row#149]
It would be convenient if this entity could add a way to format a number with commas separating the thousands in a number. The default entity card does show the comma so it creates a mish mash of formatting.

```
type: entities
entities:
  - type: 'custom:multiple-entity-row'
    entity: sensor.power_phase_a
    name: Phase A
    entities:
      - entity: sensor.shellyem3_channel_a_voltage
        name: false
  - type: 'custom:multiple-entity-row'
    entity: sensor.power_phase_b
    name: Phase B
    entities:
      - entity: sensor.shellyem3_channel_b_voltage
        name: false
  - type: divider
  - entity: sensor.power_total
```

![Capture2](https://user-images.githubusercontent.com/28744698/100294532-0f477900-2f55-11eb-9572-ac6d31099ac6.PNG)
