### ISSUE TITLE
FR: add toggle-lock

### ISSUE THREAD

**Issue by Mariusthvdb** [benct/lovelace-multiple-entity-row#152]
to toggle options please?

Using your card allows for very condensed cards, only thing left (for me) is the option to show a lock on a toggle for certain switches. So we don't accidentally toggle those.

Would you please consider adding support for this? Hold the entity, makes the lock open and require a second action to toggle. Maybe even add some confirmation (are your sure?) and then the actual toggle takes place.

Thanks for considering!

**Comment by benct** [comment]
This is probably more difficult than it looks (because of hold actions etc.). Will consider adding support at some point if it's not too complicated.

Confirmation might be supported already with `tap_action: toggle` and `confirmation: true`(?)

**Comment by Mariusthvdb** [comment]
ok, let me have a look at that. thing is, I have a full set of multiple-entity-rows, created automatically using a decluttering card, 

```
  - type: custom:decluttering-card
    template: switches_multiple_entity
    variables:
      - entity: everspring_ikea_hub
    tap_action: toggle
    confirmation: true
```

and the Lovelace card:


```
.....
  - type: custom:decluttering-card
    template: switches_multiple_entity
    variables:
      - entity: cv_zolder

  - type: custom:decluttering-card
    template: switches_multiple_entity
    variables:
      - entity: zonneboiler_zolder

  - type: divider

  - type: custom:decluttering-card
    template: switches_multiple_entity
    variables:
      - entity: everspring_ikea_hub
.....

showing like:

<img width="493" alt="Schermafbeelding 2020-12-03 om 13 39 39" src="https://user-images.githubusercontent.com/33354141/101019303-1120c600-356d-11eb-89cf-5a9f95713f39.png">

I only need a few of these to have the lock enabled, take the bottom one:
```
  - type: custom:decluttering-card
    template: switches_multiple_entity
    variables:
      - entity: everspring_ikea_hub
```

how would you suggest to use the tap_action: toggle
