### ISSUE TITLE
Incorrect states on secondary_info

### ISSUE THREAD

**Issue by phrfpeixoto** [benct/lovelace-multiple-entity-row#156]
Hi!

First and foremost, excellent work! Congrats!
I'm having an issue with entity states not showing correctly on the `secondary info`
IE: take a door/window contact sensor that works as a `binary_sensor`:

Entity:
![Screen Shot 2020-12-08 at 18 47 30](https://user-images.githubusercontent.com/10242829/101545381-efb54500-3985-11eb-8248-61e69f1f75b9.png)

The correct values for this entity should be `Open` or `Closed`

Card:
```yaml
- entity: binary_sensor.janela_central_da_sala_contact
  type: 'custom:multiple-entity-row'
  icon: 'mdi:window-closed-variant'
  show_state: true
  secondary_info:
    entity: binary_sensor.janela_central_da_sala_contact
  entities:
    - entity: sensor.janela_do_escritorio_battery
      name: Bateria
    - entity: sensor.janela_do_escritorio_linkquality
      name: Link
```
Note that I'm using the exact same entity reference for both the `entity` itself and the `secondary_info`

Which renders as:
![Screen Shot 2020-12-08 at 18 50 08](https://user-images.githubusercontent.com/10242829/101545621-4a4ea100-3986-11eb-89ea-8f47c80a90ef.png)

Here we can see that the state at the end (which I would like to hide) shows the correct `Open` value, while the `secondary_info` value shows as `on`

I can try to help, but I'm not JS/Frontend developer. Please point me in the right direction.
