### ISSUE TITLE
Templating attribute value

### ISSUE THREAD

**Issue by twproject** [benct/lovelace-multiple-entity-row#158]
Hi all,
i created a card to show some shelly information, is possible to change false or true of an attribute value to another text?

```
type: 'custom:auto-entities'
show_empty: false
card:
  type: entities
  title: Shelly
filter:
  exclude:
    - attributes:
        friendly_name: Shelly*
  include:
    - entity_id: '*shelly*'
      attributes:
        ip_address: '! none'
        has_firmware_update: '! none'
      options:
        type: 'custom:multiple-entity-row'
        show_state: true
        toggle: true
        entities:
          - attribute: ip_address
            name: IP
          - attribute: has_firmware_update
            name: FW
```

I tried with no luck

```
          - attribute: >-
               {% if state_attr(config.entity, 'has_firmware_update') %}
                 Latest
               {% else %}
                 Upgrade
               {% endif %}
```

Thanks
