### ISSUE TITLE
Custom more-info entity

### ISSUE THREAD

**Issue by vassilis-panos** [benct/lovelace-multiple-entity-row#161]
Hi, I'm really missing the custom entity at more-info tap action. 
```
- type: 'custom:multiple-entity-row'
  entity: switch.office_ac
  tap_action:
     action: more-info
     entity: climate.office_ac
```
Is there a chance it will come back?
