### ISSUE TITLE
Enable setting "Type" field for Entities for integration with the slider-entity-row custom card 

### ISSUE THREAD

**Issue by tom-erik-l** [benct/lovelace-multiple-entity-row#163]
It would be neat to be able to combine multiple entities per row, where some of them might be sliders.

See the below repository for usage of the slider-entity-row custom card:
https://github.com/thomasloven/lovelace-slider-entity-row

A possible example could be having a brightness slider and a color temperature slider side-by-side.

**Comment by benct** [comment]
Setting the `type` field would indicate rendering another card inside the row, which neither this card or slider-entity-row is designed to do. A better solution is to actually support HA sliders when specified by a some config option. Not sure I'll have the time to implement that in near future, but I'll leave the issue open as a FR.

**Comment by GerdBlomb** [comment]
Not sure if this is the same topic (i think so):

I have a number_input defined as slider with min, max and step. When i use that in an "entities" card i get the value and the slider to modify that value. Thats ok.

When i use the same number_input in multiple-entity-row i get only the value and no slider. I can not change the value. Issue.

**Comment by bjeanes** [comment]
I'd love support for `input_number`s in general, but in lieu of that I have done something like:

<img width="366" alt="Screen Shot 2022-02-16 at 5 46 14 pm" src="https://user-images.githubusercontent.com/2560/154210859-44b39948-074d-41fd-b5f9-5dacfbc7f6b1.png">

The basic pattern for each of those is:

```yaml
  - entity: sensor.tent_reservoir_ph
    name: pH
    type: custom:multiple-entity-row
    show_state: false
    secondary_info:
      entity: sensor.tent_reservoir_ph
      name: false
      unit: false
    entities:
      - icon: mdi:chevron-down
        styles:
          margin: 0
        tap_action:
          action: call-service
          service: input_number.decrement
          service_data:
            entity_id: input_number.minimum_ph
      - entity: input_number.minimum_ph
        name: min
        unit: false
        styles:
          margin: 0
      - icon: mdi:chevron-up
        tap_action:
          action: call-service
          service: input_number.increment
          service_data:
            entity_id: input_number.minimum_ph
      - icon: mdi:chevron-down
        styles:
          margin: 0
        tap_action:
          action: call-service
          service: input_number.decrement
          service_data:
            entity_id: input_number.maximum_ph
      - entity: input_number.maximum_ph
        styles:
          margin: 0
        name: max
        unit: false
      - icon: mdi:chevron-up
        tap_action:
          action: call-service
          service: input_number.increment
          service_data:
            entity_id: input_number.maximum_ph
```
