### ISSUE TITLE
secondary_info: last-changed empty

### ISSUE THREAD

**Issue by TroLoos** [benct/lovelace-multiple-entity-row#165]
Hi, it bothers me for quite a while now... but it seems like secondary_info doesn't really get proper values for attributes...

When I try to use last-change attribute - it is always: "Never".

I've made a sample on the following screenshot for the same entity.

![screenshot](https://user-images.githubusercontent.com/24640072/105195185-aafefb00-5b3a-11eb-90be-c9fc38b9b4f1.png)

What am I doing wrong?

**Comment by woodmj74** [comment]
Try removing the second reference of entity and secondary_info (beneath pressure):

```
type: entities
entities:
  - entity: sensor.lounge_temperature
    secondary_info: last-changed
    entities:
      - entity: sensor.lounge_humidity
        name: Humidity
      - entity: sensor.lounge_pressure
        name: Pressure
    type: 'custom:multiple-entity-row'
```

**Comment by TroLoos** [comment]
Well, it wasn't actually 2nd occurrence (duplicate), in this code there are 2 rows (entities) defined, one with default settings (built in HA), the second with lovelace-multiple-entity-row. If you look close - first displays last-changed properly, the second not at all, even though they refer to the same base entity (sensor.sensor_master_bathroom_temperature).

I did that anyway just to check and be sure, here's a result:

![screen](https://user-images.githubusercontent.com/24640072/105200230-e7812580-5b3f-11eb-89b6-0a85ae16938a.png)

**Comment by woodmj74** [comment]
doh, sorry! Didn't read it properly :-(

**Comment by LavermanJJ** [comment]
I have the same issue, that `last_changed` isn't working anymore.

```
      - type: custom:multiple-entity-row
        entity: binary_sensor.bwm_flur
        secondary_info: last-changed
        state_color: true
        name: Flur
        entities:
          - entity: sensor.brightness_flur
            name: Helligkeit
```
