### ISSUE TITLE
Set Name to false does not work

### ISSUE THREAD

**Issue by Husabert** [benct/lovelace-multiple-entity-row#168]
Hi,

I tried the 7th example *to hide the headers) but the sentence 
name: false 
does not compute

- entity: sensor.bedroom_temperature
    type: custom:multiple-entity-row
    name: Hide headers (name)
    entities:
      - entity: sensor.bedroom_min_temp
        name: false
      - entity: sensor.bedroom_max_temp
        name: false

**Comment by woodmj74** [comment]
Have you got your indention correct?

```
entity: sensor.lounge_temperature
type: 'custom:multiple-entity-row'
name: Hide headers (name)
entities:
  - entity: sensor.roof_temperature
    name: false
  - entity: sensor.landing_temperature
    name: false
```
![image](https://user-images.githubusercontent.com/68328701/107545882-af5f8680-6bc3-11eb-8aca-ad5aa94c4d3a.png)
