### ISSUE TITLE
Help wanted - truncate "Name" field width

### ISSUE THREAD

**Issue by damyanor** [benct/lovelace-multiple-entity-row#169]
Hi,
in reference to #134 
I found that the name field can be cut by changing flex property of the .info class. Originally the value looks like this: `flex: 1 0 30%; ` and it should be changed to ie. `flex: 1 0 0%;` However, I cannot set a proper path to override the style using card-mod plugin. Is this even possible? Here's the code of the example card (Firefox'es Inspector screenshot is better than the code itself I think to show the hierarchy):
![flex](https://user-images.githubusercontent.com/46784312/107344239-87d4c500-6ac2-11eb-9373-1d12aaed4632.png)

**Comment by ildar170975** [comment]
**How to decrease a width of the "name" field (.info.pointer.text-content) by card-mod:**
Before:
```
type: entities
entities:
  - type: 'custom:multiple-entity-row'
    entity: sun.sun
    entities:
      - entity: sun.sun
        name: xxx
        styles:
          width: 60px
      - entity: sun.sun
        name: xxx
        styles:
          width: 60px
      - entity: sun.sun
        name: xxx
        styles:
          width: 60px
      - entity: sun.sun
        name: xxx
        styles:
          width: 60px
    name: ''
    unit: ''
    icon: ''
    toggle: false
    show_state: false
    state_header: ''
    state_color: false
```
![изображение](https://user-images.githubusercontent.com/71872483/109570822-c0812080-7afb-11eb-9f25-69c281b06148.png)

After:
```
  - type: 'custom:multiple-entity-row'
    style:
      hui-generic-entity-row:
        $: |
          .info.pointer {
            flex: 1 0 0%;
          }
    entity: sun.sun
    entities:
      - entity: sun.sun
        name: xxx
        styles:
          width: 60px
      - entity: sun.sun
        name: xxx
        styles:
          width: 60px
      - entity: sun.sun
        name: xxx
        styles:
          width: 60px
      - entity: sun.sun
        name: xxx
        styles:
          width: 60px
    name: ''
    unit: ''
    icon: ''
    toggle: false
    show_state: false
    state_header: ''
    state_color: false
```
![изображение](https://user-images.githubusercontent.com/71872483/109570991-03db8f00-7afc-11eb-87c4-28152352039e.png)

I think that some time ago it was working properly, then it was changed, so we can see that some columns may be not visible...
Recently I realized this in my setup:
![изображение](https://user-images.githubusercontent.com/71872483/109571201-616fdb80-7afc-11eb-8a8b-9625a33cdffe.png)
Note that the last column is not fully visible because these 3 columns were shifted to the right - they used to be located closer to the left border:
![изображение](https://user-images.githubusercontent.com/71872483/109571402-b6abed00-7afc-11eb-8275-8ca77517482c.png)
So now I have to manually correct the "flex" property by card-mod.
