### ISSUE TITLE
Not parsing JSON attributes

### ISSUE THREAD

**Issue by LouPaloma** [benct/lovelace-multiple-entity-row#170]
(This is probably a new feature request, but...)

An attribute element should parse a valid JSON attribute list much like templates, i.e., if this is valid:

`{{ states.sensor.home_uv_index.attributes.weather.UVa }}`

then one should be able to do this:

```
    - entity: sensor.home_uv_index
      type: custom:multiple-entity-row
      name: UV Index
      secondary_info: last-changed
      entities:
        - attribute: weather.UVa
          name: UVa
        - attribute: weather.UVb
          name: UVb
```

For example, using this sensor attribute list:

`{'sensor': {'id': 'weatherStation', 'subSystem': 'uv', 'time': 179763221, 'timeStamp': '2021-02-09T16:32:18-0800'}, 'weather': {'UVa': 30.15, 'UVb': 44.05, 'index': 0.043431}, 'friendly_name': 'Home UV Index', 'icon': 'mdi:sunglasses', 'custom_ui_state_card': 'state-card-custom-ui'}`

(as parsed in the template tool via: `{{ states.sensor.home_uv_index.attributes }}`)
