### ISSUE TITLE
Width of a "name" field (.info.pointer.text-content) is not decreasing when other columns need more space

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#175]
Related to this issue:
https://github.com/benct/lovelace-multiple-entity-row/issues/169

Recently I realized that a width of a "name" field (.info.pointer.text-content) is not decreasing when other columns need more space.

The code example:
```
type: entities
entities:
  - type: 'custom:multiple-entity-row'
    entity: sun.sun
    entities:
      - entity: sun.sun
        name: xxx
        styles:
          width: 60px
      - entity: sun.sun
        name: xxx
        styles:
          width: 60px
      - entity: sun.sun
        name: xxx
        styles:
          width: 60px
      - entity: sun.sun
        name: xxx
        styles:
          width: 60px
    name: ''
    unit: ''
    icon: ''
    toggle: false
    show_state: false
    state_header: ''
    state_color: false
```
Now it looks like this:
![изображение](https://user-images.githubusercontent.com/71872483/109643881-e04d2e80-7b65-11eb-81d7-90b611621abe.png)

But it used to be like this:
![изображение](https://user-images.githubusercontent.com/71872483/109643979-f824b280-7b65-11eb-882d-a666859c33ab.png)

On my current setup I first realized it here:
![изображение](https://user-images.githubusercontent.com/71872483/109644091-17234480-7b66-11eb-9f7c-b5a147075775.png)
I do not have old screenshots, but it used to be like this:
![изображение](https://user-images.githubusercontent.com/71872483/109644180-3621d680-7b66-11eb-9249-9e1dfb6d17a2.png)

I am not an expert in CSS; according to Inspector, a possible reason may be this:
for ".info.pointer.text-content" - flex=1 0 30%
By using card-mod I managed to fix it:
```
  - type: 'custom:multiple-entity-row'
    style:
      hui-generic-entity-row:
        $: |
          .info.pointer {
            flex: 1 0 0%;
          }
```
Now it looks OK (see screenshot 2).

I wonder why this could happen.
The latest update of multiple-entity-row was on November 2020, but this change happened recently (may be about 2 weeks).
