### ISSUE TITLE
nest conditional entity in multiple entity row

### ISSUE THREAD

**Issue by Bergerie** [benct/lovelace-multiple-entity-row#177]
`type: entities
entities:
  - entities:
      - entity: sensor.floor_pump_power
        name: Power
        unit: W
    entity: switch.floor_pump_208
    icon: 'mdi:lightbulb'
    state_color: true
    toggle: false
    type: 'custom:multiple-entity-row'
  - type: conditional
    conditions:
      - entity: sensor.last_flame_out
        state_not: '00:00'
      - entity: switch.floor_pump_208
        state: 'on'
    row:
      entity: sensor.last_flame_out
      name: Flame Out
      icon: 'mdi:fire'
show_header_toggle: false`

I would like to include the currently separately shown conditional entity: sensor.last.flame as a 'conditional' multiple entity next to multiple entity: sensor.floor_pump_power. Sofar, I have been unsuccessful. Am I embarking on lost course or is it doable. If the latter, any guidance how to accomplish this.

**Comment by benct** [comment]
Never used the `conditional` card before, so not sure.. try something like this:

```
type: entities
entities:
  - type: 'custom:multiple-entity-row'
    entities:
      - entity: sensor.floor_pump_power
        name: Power
        unit: W
    entity: switch.floor_pump_208
    icon: 'mdi:lightbulb'
    state_color: true
    toggle: false
  - type: conditional
    conditions:
      - entity: sensor.last_flame_out
        state_not: '00:00'
      - entity: switch.floor_pump_208
        state: 'on'
    card:
      type: 'custom:multiple-entity-row'
      entity: sensor.last_flame_out
      name: Flame Out
      icon: 'mdi:fire'
```
