### ISSUE TITLE
Status text in the display language?

### ISSUE THREAD

**Issue by Henry-Sir** [benct/lovelace-multiple-entity-row#178]
Hello,

Is it possible to display the status text in the display language?
Currently the english text is displayed.
 
Example: thermostat

havc_action: idle  -> in German "Leerlauf"

The Thermostat card display the right text:

![grafik](https://user-images.githubusercontent.com/75314095/111886013-7937d280-89cb-11eb-8fbd-6bdc9283870d.png)

```

type: entities
entities:
  - entity: climate.wtherm_bath_eg
    type: 'custom:multiple-entity-row'
    state_color: true
    show_state: true
    toggle: false
    entities:
      - attribute: hvac_action
        name: hvac_action

```
