### ISSUE TITLE
Icons are not responsive

### ISSUE THREAD

**Issue by gitisz** [benct/lovelace-multiple-entity-row#185]
Using a combination horizontal stack and vertical stack, when viewing from a smaller device, i.e. mobile, the icons do not wrap to the next line, but instead bleed over into other cards, causing them to be difficult to use or understand.

When viewed from a web-page:
![image](https://user-images.githubusercontent.com/4492953/113465733-8362c380-9404-11eb-9983-5b2fb02035c2.png)

When viewed from mobile:
![image](https://user-images.githubusercontent.com/4492953/113465724-67f7b880-9404-11eb-8c55-1e8ff143a497.png)

```
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: gauge
                    entity: sensor.mrs_worden_battery_level
                    style: |
                      ha-card  {
                        background-color: rgba(0, 0, 0, 0.3);
                        box-shadow: none;
                      }
                    min: 0
                    max: 100
                    severity:
                      green: 75
                      yellow: 35
                      red: 0
                  - type: 'custom:multiple-entity-row'
                    entity: binary_sensor.mrs_worden_is_charging
                    show_state: false
                    state_color: true
                    name: ' '
                    entities:
                      - type: binary_sensor
                        entity: binary_sensor.mrs_worden_wifi_state
                        icon: true
                        name: false
                        state_color: true

                      - type: binary_sensor
                        entity: binary_sensor.mrs_worden_device_locked
                        icon: true
                        name: false
                        state_color: true

                      - type: binary_sensor
                        entity: binary_sensor.mrs_worden_bluetooth_state
                        icon: true
                        name: false
                        state_color: true

                      - type: binary_sensor
                        entity: binary_sensor.mrs_worden_headphones
                        icon: true
                        name: false
                        state_color: true

                      - type: button
                        icon: 'mdi:radar'
                        name: false
                        state_color: false
                        tap_action:
                          action: call-service
                          service: script.locate_wifes_phone
```
