### ISSUE TITLE
Tap_Action more-info shows primary entity not alternate

### ISSUE THREAD

**Issue by JAAlperin** [benct/lovelace-multiple-entity-row#188]
The title pretty much tells it all.  The following shows the switch more info not the media_player
`              - type: custom:multiple-entity-row
                entity: switch.sonos_power
                icon: mdi:speaker-wireless
                name: Sonos Speakers
                toggle: true
                tap_action:
                  action: more-info
                  entity: media_player.sonos`

**Comment by boybert** [comment]
Also seeing this behavior - the `entity` parameter of the `tap_action` object seems to be ignored; no matter what `entity` is defined as, the "more info" popup relates to the parent entity of the row.

Code example:
```
type: entities
entities:
  - name: Outdoors
    entity: sensor.outdoor_weather
    type: custom:multiple-entity-row
    show_state: false
    tap_action:
      action: more-info
      entity: weather.combined_weather
```
Tapping the resulting row yields a 'more info' popup for `sensor.outdoor_weather`, not `weather.combined_weather` as expected.

**Comment by wiuwiu** [comment]
I have the same situation.
```
      - type: entities
        title: "Roboty"
        show_header_toggle: true
        entities:
          - entity: sensor.roomba_battery
            name: "Odkurzacz Roomba 980"
            type: custom:multiple-entity-row
            icon: mdi:robot-vacuum
            tap_action:
              action: more-info
              entity: vacuum.roomba
```
Primary more-info card shows up instead of alternate more-info. This situation occurs only on the main entity, rest entities in the same row are OK.

**Comment by TobiasSchwarz74** [comment]
Seeing this issue as well.
Would be very nice, if this could be fixed soon.
There are a lot of situations, where this would be very helpful!

**Comment by tomlut** [comment]
I've just noticed this too. It means I cant edit input helpers used with this row. 

It looks like the repository has not been updated for 9 months. Maybe abandoned?

**Comment by roumano** [comment]
Not sure if it's the same bug :
like when it's use with `Three entities` example with 3 diferents entity, Whatever click in any-one of the tree entity, always see the same more info entity's

```yaml
type: entities
entities:
  - entity: sensor.sonde_1_temperature
    type: custom:multiple-entity-row
    name: Three entities
    entities:
      - entity: sensor.sonde_1_temperature
        tap_action:
          action: more-info
          entity: sensor.sonde_1_temperature
      - entity: sensor.sonde_2_temperature
        tap_action:
          action: more-info
          entity: sensor.sonde_2_temperature
      - entity: sensor.sonde_3_temperature
        tap_action:
          action: more-info
          entity: sensor.sonde_3_temperature
```

**Comment by benct** [comment]
> Not sure if it's the same bug

Your example is related to a new change in HA 2021.12.x (see #217).

--- 

The card does not currently support overriding the `more-info` entity for the main row (icon and name), only for additional entity objects. Will see if it can be supported somehow.

**Comment by ildar170975** [comment]
> The card does not currently support overriding the `more-info` entity for the main row (icon and name), only for additional entity objects.

I guess that this is related to HA 2021.12 too, am I right?

**Comment by maximatchev** [comment]
I have the same situation. 
Overriding entity for more-info action not working

**Comment by chaot2000** [comment]
I have a similiar situation. Using double_tap_action with a switch doesn't work.

**Comment by ReX1983** [comment]
Same issue with the footer entities and hold_action. The entity specified is ignored and more-info shows the panel of the main entity.

In this example I would like to see the more-info of cover.master_bedroom_blinds but I see instead switch.master_bedroom_blinds.
```
   - entity: switch.master_bedroom_blinds
      name: Bedroom
      hold_action:
        entity: cover.master_bedroom_blinds
        action: more-info
```

Is anyone working on this?

**Comment by ildar170975** [comment]
> footer entities and hold_action.

![изображение](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/f0dbb2c3-34db-4377-9c88-00177c42519d)

**Comment by parautenbach** [comment]
I have an issue where `double_tap_entity` is also not working on the **main entity**. 

```
              - type: custom:multiple-entity-row
                entity: switch.grid_charge_point_1
                name: 01:00-05:00
                icon: mdi:clock-time-four-outline
                state_header: Grid
                style:
                  text-align: right
                tap_action:
                  action: more-info
                  haptic: light
                double_tap_action:
                  action: toggle
                  haptic: medium
                  confirmation: true
                entities:
                  - entity: number.capacity_point_1
                    name: Target
                    style:
                      text-align: right
```

**Comment by ildar170975** [comment]
@parautenbach 
Tested with a bit simpler code:
```
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: switch.test_switch
    state_header: Grid
    tap_action:
      action: more-info
    double_tap_action:
      action: toggle
      confirmation: true
    entities:
      - entity: input_number.test_number
        name: Target
```
May be I am missing smth - but seems to be working as expected, no?
![a0](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/af1d379b-4344-467a-be51-0d56352afce6)
