### ISSUE TITLE
Input_datetime formatted in 12H AM/PM, possible to have it formatted in 24H?

### ISSUE THREAD

**Issue by DJKalz** [benct/lovelace-multiple-entity-row#189]
First of all this is a great addition to the entities card and is so much more powerful and useful, so thanks for the hard work and releasing it to the community!!

I’m having a slight issue with formatting when using this card when using the helpers input_datetime.

When I add the datetime helpers to the card it shows the datetime in 12H AM / PM format. I would like it to be displayed as HH:mm, in 24 hour format.

Here’s the code I’m using with a screenshot of what it displays, and thanks in advance for any help.

```
type: entities
title: Schedule 1
show_header_toggle: false
entities:
  - entity: input_boolean.day_1_1
    type: 'custom:multiple-entity-row'
    show_state: false
    state_color: true
    tap_action:
      action: none
    entities:
      - entity: input_boolean.day_1_1
        toggle: true
        name: false
      - entity: input_datetime.workday_1_1
        name: Work day
      - entity: input_number.workday_1_1
        name: °C
        format: precision0
      - entity: input_datetime.offday_1_1
        name: Off day
      - entity: input_number.offday_1_1
        name: °C
        format: precision0
```

![image](https://user-images.githubusercontent.com/82683985/117015015-46cb0600-ace9-11eb-8d0e-d945b56d03db.png)

PS, I don't think I can use a senor template and format it because I am using this card to also act as the input, when the user clicks on the field a window pops up which allows you to set the temperature.

**Comment by tobi-bo** [comment]
I think, the card should respect the time format in user settings:
![image](https://user-images.githubusercontent.com/59911374/140051720-fa9743bf-e953-44bb-818e-0e66b4989076.png)

But it seems, that this is ignored:
![image](https://user-images.githubusercontent.com/59911374/140051957-82400198-5b2f-4412-bcdd-dedb9b88924c.png)

**Comment by benct** [comment]
This card uses [custom-card-helpers](https://github.com/custom-cards/custom-card-helpers) for formatting time values, which seem to not have implemented support for AM/PM yet. Would suggest making an issue there and they'll hopefully add it soon.

**Comment by benct** [comment]
Should (in theory) be fixed in version `4.4.0`. Let me know if not.

**Comment by ildar170975** [comment]
Unfortunately, values between 00:00 & 00:59 are displayed wrong:
```
  - type: entities
    entities:
      - input_datetime.test_datetime
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: input_datetime.test_datetime
            name: time
        show_state: false
```
![изображение](https://user-images.githubusercontent.com/71872483/147217690-28402029-ab0d-4627-9d91-285e2ec6ace7.png)
