### ISSUE TITLE
Allow Default values for entities/allow still creating the row element

### ISSUE THREAD

**Issue by kamtschatka** [benct/lovelace-multiple-entity-row#191]
I am using the entity row in an auto-entities card and have combined it with a templating card. This way I can easily show all information about my docker containers, but the problem is, some of them do not have e.g. the TotalDown information.
```
- entity: '${getEntityId(''+++entityid+++'') + ''_network_total_down''}'
  name: Total Down
  styles:
    width: 90px
    text-align: left
```

Resulting in this: 
![image](https://user-images.githubusercontent.com/22147234/118890513-1b5a3500-b8ff-11eb-9c4c-850ac7cc599c.png)

Would be great to add a config flag that will still create the entry with all the stylings, so the layout doesn't get disturbed. Ideally a configurable message or icon would be shown, so the user can define that and make sure the layout doesn't get messed (I am thinking if there is a default message like "failed to find entity", then it will be too long for some layouts and will be annoying again)

Is this something that makes sense to put in there?
If yes let me know. I am also willing to contribute the code for that, if that helps.
