### ISSUE TITLE
HA 2021.6 Lit version upgrade

### ISSUE THREAD

**Issue by hmmbob** [benct/lovelace-multiple-entity-row#192]
This card is importing Lit in a way that might break in HA 2021.6 which ships with Lit 2.0

For more information, see https://developers.home-assistant.io/blog/2021/05/19/lit-2.0/

**Comment by pooyashahidi** [comment]
Is that why this happens?
![before-after](https://user-images.githubusercontent.com/5418119/120623794-5496b700-c460-11eb-8485-45b7e2187f82.png)

**Comment by hmmbob** [comment]
Could be, yet mine are still fine. What's your config?

**Comment by pooyashahidi** [comment]
for example this:
```
type: custom:multiple-entity-row
entity: sensor.livingroom_temp_sensor_temperature
icon: svg:living-room
name: Living room
show_state: false
entities:
  - entity: sensor.livingroom_temp_sensor_temperature
    name: ' '
    unit: °C
  - entity: sensor.livingroom_temp_sensor_humidity
    name: ' '
    unit: '%'
```

![image](https://user-images.githubusercontent.com/5418119/120625604-2b772600-c462-11eb-9111-8341363a9e36.png)
