### ISSUE TITLE
state_color for water_heater

### ISSUE THREAD

**Issue by ARNik** [benct/lovelace-multiple-entity-row#196]
I have Redmond RK-171S kettle in HA.
It look like water_heater.kettle_rk_m171s and have two states:
- off
- electric

state_color does not work in my case. What can I do to fix it?

![image](https://user-images.githubusercontent.com/3407744/122372191-25f10400-cf69-11eb-940d-f998d3b28635.png)

**Comment by ARNik** [comment]
```
  - entity: switch.kettle_rk_m171s
    type: custom:multiple-entity-row
    show_state: true
    state_color: true
    toggle: true
    secondary_info: last-updated
    entities:
      - entity: water_heater.kettle_rk_m171s
        attribute: temperature
        name: Target
        unit: '°C'
      - entity: water_heater.kettle_rk_m171s
        attribute: current_temperature
        name: Current
        unit: '°C'
      - entity: sensor.status_rk_m171s
        name: State
```

![image](https://user-images.githubusercontent.com/3407744/122372475-5f297400-cf69-11eb-92fa-66818e3e2cb2.png)
![image](https://user-images.githubusercontent.com/3407744/122372714-939d3000-cf69-11eb-952d-84c595e19ca0.png)
