### ISSUE TITLE
Time is displayed wrong: "24:15"

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#198]
When displaying a datetime value like "00:15" with "format: datetime", it is displayed as "24:15".
Original value is "'2021-07-06T21:15:02+00:00'" (= 00:15 in GMT+3).
```
  - type: custom:multiple-entity-row
    entity: device_tracker.life360_iphone_ira
    entities:
      - entity: device_tracker.life360_iphone_ira
        attribute: at_loc_since
        name: false
        format: datetime
    show_state: false
    secondary_info:
      entity: device_tracker.life360_iphone_ira
      attribute: at_loc_since
      name: false
      format: datetime
```
![image](https://user-images.githubusercontent.com/71872483/124824957-b1afec00-df7b-11eb-96f6-188965e73803.png)

**Comment by ildar170975** [comment]
Probably related to this: https://github.com/home-assistant/frontend/issues/9379

**Comment by ildar170975** [comment]
Seems to be solved:
![image](https://user-images.githubusercontent.com/71872483/137817418-fc65e557-fa92-4f43-9e7e-cb65de1d55da.png)

**Comment by ildar170975** [comment]
2023.4.4
Time is still displayed wrong:
```
  - type: entities
    entities:
      - input_datetime.test_datetime
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: input_datetime.test_datetime
            name: time
        show_state: false
        secondary_info:
          entity: input_datetime.test_datetime
          name: ' '
```
![image](https://user-images.githubusercontent.com/71872483/232786407-0ebf1441-7504-42d7-9c19-145bc1f6dee3.png)

**Comment by ildar170975** [comment]
2024.2.1
4.5.0
The glitch seems to appear only if `format: datetime` is defined:
```
  - type: entities
    entities:
      - input_datetime.test_datetime

      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: input_datetime.test_datetime
        show_state: false
        secondary_info:
          entity: input_datetime.test_datetime
          name: false

      - type: custom:multiple-entity-row
        entity: input_datetime.test_datetime
        entities:
          - entity: input_datetime.test_datetime
            format: datetime
        show_state: false
        secondary_info:
          entity: input_datetime.test_datetime
          name: false
          format: datetime
```
![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/d16e5cd1-7807-4d5e-8495-d6133a86447a)

**Comment by ildar170975** [comment]
2024.5
See no issue:
```
type: entities
entities:
  - input_datetime.test_datetime
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - entity: input_datetime.test_datetime
        name: time
    show_state: false
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - entity: input_datetime.test_datetime
        name: time
        format: datetime
    show_state: false
```
![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/c7255169-ea30-4cfd-a7d3-a634c3afe06c)

Closing
