### ISSUE TITLE
Format: relative for secondary info doesn't display on mobile

### ISSUE THREAD

**Issue by gvssr** [benct/lovelace-multiple-entity-row#205]
When using the format: relative option for a secondary info it doesn't apply the formatting on mobile (iOS 14). See below examples ("_Last backup_"):

**Desktop**
![image](https://user-images.githubusercontent.com/61377476/132012673-1c65a0a3-19b4-4ace-aefd-e9ea7c38cd2b.png)

**Mobile**
![image](https://user-images.githubusercontent.com/61377476/132012764-d647524c-fcad-4be1-a831-dc2c14bf22ac.png)

**Code**
```
entity: binary_sensor.remote_ui
type: custom:multiple-entity-row
state_color: true
show_state: false
name: Home Assistant Cloud
secondary_info:
  entity: sensor.samba_backup
  name: Last backup
  format: relative
  attribute: last_backup
entities:
  - entity: sensor.samba_backup
    name: Backup
  - entity: binary_sensor.remote_ui
    name: Cloud Status
```
