### ISSUE TITLE
Can't update an input_number with decimal value from IOS app

### ISSUE THREAD

**Issue by duvalale** [benct/lovelace-multiple-entity-row#211]
Hello,

I have this card with input_number entities displayed in a multiple-entity-row card :
`````
      - name: Aujourd'hui
        entity: input_number.today_running
        icon: mdi:calendar-edit
        show_state: false
        type: custom:multiple-entity-row
        entities:
          - entity: input_number.today_running
            name: Footing
          - entity: input_number.today_cycling
            name: Vélo
          - entity: input_number.today_swimming
            name: Nage
`````

I can update the input_numbers however I want from a browser, but impossible to update it with a decimal value from the IOS app, it won't take the coma/point, just the numbers.
I tried adding 
```
format: precision1
``` 
with no success.
If I put the same ````input_number```` in an entity card, I have no problem.

Do you have any idea how to fix this ?

Thanks
