### ISSUE TITLE
STate_color for first and second switch

### ISSUE THREAD

**Issue by pepsonEL** [benct/lovelace-multiple-entity-row#214]
Hi
I add to Home Assistant two switches by your custom card. I also add option state_color as  true but is show color icon only for switch.multi_relay_0_16 but for second switch.multi_relay_0_15 not show icon in color. Is any chance to also show icon color for this ? 

![switch](https://user-images.githubusercontent.com/71824185/142779215-925d4614-7e86-481b-a3fa-38963a54e675.jpg)
```
type: entities
entities:
  - entity: sensor.lazienka_parter_temperature
    type: custom:multiple-entity-row
    name: Temp./Wilg.
    state_header: Temperatura
    entities:
      - entity: sensor.lazienka1_fan_bme280_humidity
        name: Wilgotność
  - entity: switch.multi_relay_0_16
    toggle: true
    type: custom:multiple-entity-row
    name: Oświetlenie
    state_header: Sufit
    state_color: true
    entities:
      - entity: switch.multi_relay_0_15
        name: Kinkiet
        toggle: true
state_color: true
title: Łazienka parter
show_header_toggle: false
```
