### ISSUE TITLE
Multiple entities row card does not toggle on tablet or mobile but does toggle on desktop

### ISSUE THREAD

**Issue by AbhiOommen** [benct/lovelace-multiple-entity-row#216]
I'm running 2021.12.0b3 and the multiple entity row card is widely used in my dashboard,  it started not working right on my Fire tablet and my phone (android). But works well on the desktop. 

So with `toggle: true` set it doesn't toggle the switches, as it used to before. the weird thing is that it is only a problem on my mobile devices, kindle and android phone, but works well on the desktop.

This started recently after I updated to 12.0b - not sure if there was some breaking change that affected this card.

Below is the config used for one of the cards and also can send you a video to show what exactly happens, if needed.

```
      - type: entities
        entities:
          - entity: group.big_room_lights
            name: Big
            toggle: true
            state_header: All
            state_color: true
            icon: "mdi:lightbulb-group"
            type: custom:multiple-entity-row
            entities:
              - entity: switch.big_bedroom_light
                name: Bedroom
                toggle: true
              - entity: switch.big_vanity
                name: Vanity
                toggle: true
              - entity: switch.kids_bathroom
                name: Bathroom
                toggle: true
          - entity: group.small_room_lights
            name: Small
            toggle: true
            state_header: All
            state_color: true
            icon: "mdi:lightbulb-group"
            type: custom:multiple-entity-row
            entities:
              - entity: switch.small_bedroom_light
                name: Bedroom
                toggle: true
              - entity: switch.small_vanity
                name: Vanity
                toggle: true
              - entity: switch.small_closet_light
                name: Closet
                toggle: true   
```
