### ISSUE TITLE
Recent update 4.4.0 broke relative / total time display

### ISSUE THREAD

**Issue by kineticscreen** [benct/lovelace-multiple-entity-row#219]
![image](https://user-images.githubusercontent.com/39250334/147191109-fcbf1270-f77b-4fa7-930f-f22b36769825.png)

Until the update an hour or so ago, this would show correctly as "in 1 hour" or etc.
```
type: custom:multiple-entity-row
entity: sensor.3d_printer_status
  - entities:
      - entity: sensor.octoprint_estimated_finish_time
        name: Remaining
        format: total
      - entity: sensor.3d_printer_today_s_consumption
        name: Today
secondary_info:
   entity: sensor.3d_printer_status
   name: ' '
```

**Comment by WarC0zes** [comment]
same issue.
```
            - entity: sensor.last_boot
              type: custom:multiple-entity-row
              show_state: false
              entities:
                - entity: sensor.last_boot
                  name: DERNIER DEMARRAGE
                  format: total
                - entity: sensor.temps_online
                  name: TEMPS EN LIGNE
                  format: total
```
![format](https://user-images.githubusercontent.com/91471397/147203091-5a071d22-5cf4-4551-836e-e7c154335de6.jpg)

**Comment by tamimology** [comment]
Yes same for me. I was going to report the issue but I saw someone got me first.

I just rolled back to version 4.3.0

![Screenshot from 2021-12-23 18-50-32](https://user-images.githubusercontent.com/90429593/147206914-27297e1e-469f-4bc0-8352-826b8b79ca3a.png)

**Comment by andrewjswan** [comment]
Same for me ...

**Comment by ildar170975** [comment]
Time formats stopped working - see these examples for `time`, `datetime` & `relative`:
```
  - type: entities
    entities:
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.test_timestamp
            name: default
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.test_timestamp
            name: time
            format: time
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.test_timestamp
            name: datetime
            format: datetime
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.test_timestamp
            name: relative
            format: relative
        show_state: false
```
![изображение](https://user-images.githubusercontent.com/71872483/147214020-073494cb-daf4-4e4e-8b0b-4d2852ec0896.png)
Also, it is strange that the 1st line w/o format gives a formatted string.
Probably this formatted string should be for some other format.

**Comment by bcutter** [comment]
Confirmed, being introduced with latest v4.3.0 update.

![image](https://user-images.githubusercontent.com/13799156/147255775-e78ec39e-e012-4b68-a3a3-7d778d7055eb.jpeg)

Can we please stop introducing new bugs with every update of the last weeks here? A bit of testing before rollout would be great...

**Comment by rAdziuB** [comment]
I have the same issue with formatting "date":
`          - entity: sensor.github_wled_version
            type: custom:multiple-entity-row
            state_header: 'Last Release:'
            name: WLED
            icon: 'mdi:led-strip-variant'
            entities:
              - attribute: published_at
                name: "Release Date:"
                format: date
          - entity: sensor.github_tasmota_version
            type: custom:multiple-entity-row
            state_header: 'Last Release:'
            name: Tasmota
            icon: 'mdi:home-automation'
            entities:
              - attribute: published_at
                name: "Release Date:"
                format: date
![2021-12-23_16-05-21](https://user-images.githubusercontent.com/71127566/147258550-00022d12-cc9b-403c-a4f6-fa4fde71127f.jpg)
`

**Comment by benct** [comment]
> Can we please stop introducing new bugs with every update of the last weeks here? A bit of testing before rollout would be great...

There are a thousands of different ways to configure this card, so it's impossible to test everything. I do this in my free time, for free, so If you cant handle bugs, stop updating the card or stop using _custom_ cards at all..

**Comment by ildar170975** [comment]
I agree with benct. Everyone should participate and cooperate if we all need a good product. 
Thank you very much for your efforts, benct!

**Comment by bcutter** [comment]
> > Can we please stop introducing new bugs with every update of the last weeks here? A bit of testing before rollout would be great...
> 
> 
> 
> There are a thousands of different ways to configure this card, so it's impossible to test everything. I do this in my free time, for free, so If you cant handle bugs, stop updating the card or stop using _custom_ cards at all..

Seems to be a structural issue, not to be meant offending you. I mean there are no release channels in HACS. If there would be e. g. a stable and a testing channel... that would improve things: you wouldn't need to test things on your own and would get more test users and less "surprised" users when being on the stable path :-)

**Comment by ildar170975** [comment]
Confirm this for entities:
```
type: vertical-stack
cards:
  - type: markdown
    content: |
      Проблема 115 - CLOSED
      format не работает для timestamp
    style: 'ha-card { color: red; }'
  - type: entities
    entities:
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.test_timestamp
            name: default
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.test_timestamp
            name: time
            format: time
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.test_timestamp
            name: datetime
            format: datetime
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.test_timestamp
            name: relative
            format: relative
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.test_timestamp
            name: total
            format: total
        show_state: false
      - type: section
      - type: custom:multiple-entity-row
        entity: sensor.test_timestamp
        name: default
        entities:
          - entity: sun.sun
        show_state: true
      - type: custom:multiple-entity-row
        entity: sensor.test_timestamp
        name: time
        format: time
        entities:
          - entity: sun.sun
        show_state: true
      - type: custom:multiple-entity-row
        entity: sensor.test_timestamp
        name: datetime
        format: datetime
        entities:
          - entity: sun.sun
        show_state: true
      - type: custom:multiple-entity-row
        entity: sensor.test_timestamp
        name: relative
        format: relative
        entities:
          - entity: sun.sun
        show_state: true
      - type: custom:multiple-entity-row
        entity: sensor.test_timestamp
        name: total
        format: total
        entities:
          - entity: sun.sun
        show_state: true
      - type: section
      - type: custom:multiple-entity-row
        entity: sun.sun
        name: default
        secondary_info:
          entity: sensor.test_timestamp
          name: ' '
        entities:
          - entity: sun.sun
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        name: time
        secondary_info:
          entity: sensor.test_timestamp
          name: ' '
          format: time
        entities:
          - entity: sun.sun
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        name: datetime
        secondary_info:
          entity: sensor.test_timestamp
          name: ' '
          format: datetime
        entities:
          - entity: sun.sun
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        name: relative
        secondary_info:
          entity: sensor.test_timestamp
          name: ' '
          format: relative
        entities:
          - entity: sun.sun
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        name: total
        secondary_info:
          entity: sensor.test_timestamp
          name: ' '
          format: total
        entities:
          - entity: sun.sun
        show_state: false
```
![изображение](https://user-images.githubusercontent.com/71872483/147285921-bb729f70-e848-4061-a824-65b22e9fe206.png)

**Comment by ildar170975** [comment]
Do not confirm this for last-changed & last-updated attributes:
```
  - type: entities
    entities:
      - type: custom:multiple-entity-row
        entity: fan.xiaomi_mijia_300_1
        secondary_info: format default
        entities:
          - attribute: last-changed
            name: last-changed
          - attribute: last-updated
            name: last-updated
        show_state: false
      - type: custom:multiple-entity-row
        entity: fan.xiaomi_mijia_300_1
        secondary_info: format datetime
        entities:
          - attribute: last-changed
            name: last-changed
            format: datetime
          - attribute: last-updated
            name: last-updated
            format: datetime
        show_state: false
      - type: custom:multiple-entity-row
        entity: fan.xiaomi_mijia_300_1
        secondary_info: format total
        entities:
          - attribute: last-changed
            name: last-changed
            format: total
          - attribute: last-updated
            name: last-updated
            format: total
        show_state: false
```
![изображение](https://user-images.githubusercontent.com/71872483/147286087-948c5061-5db0-438a-8931-4357e6e9dca8.png)
