### ISSUE TITLE
Numbers are formatted not accordingly to global settings

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#220]
The card should use global format settings:
![изображение](https://user-images.githubusercontent.com/71872483/147254809-abc87cfb-bf58-4ec5-8897-ab8170308e23.png)

This card contains:
- conventional `input_number` row;
- `multiple-entity-row` with the same row with different formats.

Note that:
- the conventional row displays WRONG format (frontend issue);
- `multiple-entity-row` displays WRONG format in some cases.

![изображение](https://user-images.githubusercontent.com/71872483/147254492-6f812219-5fac-4f50-b77f-a6dfcf2fe272.png)
```
  - type: entities
    entities:
      - entity: input_number.test_negative_1
        name: test value
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: input_number.test_negative_1
            name: unformatted
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: input_number.test_negative_1
            name: invert
            format: invert
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: input_number.test_negative_1
            name: kilo
            format: kilo
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: input_number.test_negative_1
            name: precision
            format: precision4
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: input_number.test_negative_1
            name: position
            format: position
        show_state: false
```

Now, lets choose "None" format:
![изображение](https://user-images.githubusercontent.com/71872483/147255112-314d6d38-cbba-4e42-b7a6-af5afeebdc51.png)

The card now shows RIGHT format:
![изображение](https://user-images.githubusercontent.com/71872483/147255309-004d6c6a-3b99-4f6d-ab7f-bfd6b6fadb97.png)

**Comment by bcutter** [comment]
See https://github.com/benct/lovelace-multiple-entity-row/pull/212#issuecomment-997214320 and following. Might be related to the same root cause.

Introduced with v4.3.0 I think.

**Comment by benct** [comment]
Guess I missed `numberFormat` on `invert` and `position`. Anything else?

**Comment by ildar170975** [comment]
> Anything else?

No, I think only these two options are with problems.

**Comment by ildar170975** [comment]
Confirm (Win10x64, Chrome):
![изображение](https://user-images.githubusercontent.com/71872483/147284064-c26a9d9b-03de-4bfd-bddb-714ea692cdc2.png)

**Comment by bcutter** [comment]
Have a look at https://community.home-assistant.io/t/multiple-entity-row-card-local-number-formatting-update-broke-view/370718 for examples when this local number awareness feature is going too far.

**Comment by ildar170975** [comment]
Here is one more issue - again formatting does not work.

There are 2 sensors from `systemmonitor`:
- sensor.memory_free
- sensor.memory_use

This sensor is a sum of those sensors:
```
  - platform: template
    sensors:
      memory_total:
        unit_of_measurement: MB
        icon_template: mdi:chip
        value_template: >-
          {% set FREE = 'sensor.memory_free' -%}
          {%- set USE = 'sensor.memory_use'-%}
          {{ ((states(FREE)|float) + (states(USE)|float)) | round(1) }}
```
And here is a card:
```
  - type: entities
    entities:
      - entity: sensor.memory_free
      - entity: sensor.memory_use
      - entity: sensor.memory_total
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.memory_free
            name: free
          - entity: sensor.memory_free
            name: free
            unit: false
          - entity: sensor.memory_use
            name: use
          - entity: sensor.memory_total
            name: total
            unit: false
          - entity: sensor.memory_total
            name: total
        show_state: false
```
The same value is displayed differently if it is w/o unit:
![изображение](https://user-images.githubusercontent.com/71872483/147382751-da0e7fbe-55ee-4616-ab54-5f00e379db20.png)

My guess that it could be connected to using `round(...)` function in `value_template`.

Current settings:
```
![изображение](https://user-images.githubusercontent.com/71872483/147382760-35dea2e3-ec3a-44b8-b17b-8786be25eee6.png)
```
