### ISSUE TITLE
secondary_info can't access or format last-changed

### ISSUE THREAD

**Issue by peledzius** [benct/lovelace-multiple-entity-row#221]
I can't access nor format <code>last-changed</code> attribute inside main entity. Same with different entity.
<blockquote>Does not work with main entity:
<pre><code>- entity: binary_sensor.bedroom_motion_sensor
  type: custom:multiple-entity-row
  secondary_info:
    attribute: last-changed
    format: time
</code></pre></blockquote>
<blockquote>Doesn't work with different entity:
<pre><code>- entity: binary_sensor.bedroom_motion_sensor
  type: custom:multiple-entity-row
  secondary_info:
    entity: binary_sensor.template_bedroom_motion_sensor
    attribute: last-changed
</code></pre></blockquote>

**Comment by ildar170975** [comment]
> I can't format `last-changed` attribute inside main entity

May be same as this: https://github.com/benct/lovelace-multiple-entity-row/issues/219#issuecomment-1000497417
Format is not applied for the `last-changed` & `last-updated` attributes for secondary entities.



> Also can't access this attribute with different entity_id.

Do not confirm this: a value of `last-updated` is displayed for another entity:
```
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - entity: sun.sun
      - entity: sun.sun
    show_state: false
    secondary_info:
      entity: person.ildar
      attribute: last-updated
      name: ' '
```
![изображение](https://user-images.githubusercontent.com/71872483/147374507-f58ec48a-d47c-4e0b-85b2-1cc3644888df.png)
