### ISSUE TITLE
secondary_info: not displayed ALWAYS if "hide_unavailable: true"

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#222]
If `last-changed` or `last-updated` are selected for `secondary_info`, it is not displayed if `hide_unavailable: true` set.
The code:
```
  - type: entities
    entities:
      - type: custom:multiple-entity-row
        entity: sun.sun
        name: "hide_unavailable: false"
        entities: &ref_entities
          - entity: sun.sun
          - entity: sun.sun
        show_state: false
        secondary_info:
          attribute: last-changed
      - type: custom:multiple-entity-row
        entity: sun.sun
        name: "hide_unavailable: true"
        entities: *ref_entities
        show_state: false
        secondary_info:
          attribute: last-changed
          hide_unavailable: true
```
![изображение](https://user-images.githubusercontent.com/71872483/147374780-63b6a0ea-ecf6-47cf-9fbd-0b77d6509104.png)
