### ISSUE TITLE
Additional entities not always visible

### ISSUE THREAD

**Issue by ShadyMCShadesen** [benct/lovelace-multiple-entity-row#223]
Hey, i've tried to get my switches into one row together with the current state of a gate. The problem is now that the entities are simply not rendered.

### Screenshot (Card 1):
![Screenshot of the entities card 1](https://i.imgur.com/mmiwJ8A.png)
### Card 1 yaml:
```yaml
type: entities
entities:
  - entity: binary_sensor.pi_x_haupttor_geschlossen
    type: custom:multiple-entity-row
    name: Zustand
    
    entites: # this part is not rendered
      - entity: switch.pi_x_haupttor_auf
        name: false
        icon: true
        state_color: true
        tap_action:
          action: toggle
          confirmation:
            text: Soll das Haupttor geöffnet werden?
      - entity: switch.pi_x_haupttor_stop
        name: false
        icon: true
        state_color: true
      - entity: switch.pi_x_haupttor_zu
        name: false
        icon: true
        state_color: true
        tap_action:
          action: toggle
          confirmation:
            text: Soll das Haupttor geschlossen werden?

  - type: section
  - entity: sensor.pi_x_haupttor_temperatur
    type: custom:multiple-entity-row
    icon: mdi:chip
    name: Sensoren
    show_state: false
    entities:
      - entity: sensor.pi_x_haupttor_temperatur
        name: Temperatur
      - entity: sensor.pi_x_haupttor_luftfeuchtigkeit
        name: Luftfeuchtigkeit
      - entity: sensor.pi_x_haupttor_druck
        name: Druck
title: Haupttor
state_color: true
footer: # but the switches are available because here they work just fine (just for demonstration, i want to remove the footer part)
  type: buttons
  entities:
    - entity: switch.pi_x_haupttor_auf
      name: Auf
      tap_action:
        action: toggle
        confirmation:
          text: Soll das Haupttor geöffnet werden?
    - entity: switch.pi_x_haupttor_stop
      name: Stop
    - entity: switch.pi_x_haupttor_zu
      name: Zu
      tap_action:
        action: toggle
        confirmation:
          text: Soll das Haupttor geschlossen werden?
```

**But in the following card it works just fine?**

### Screenshot (Card 2):
![Screenshot of the entities card 2](https://i.imgur.com/urEfenl.png)
### Card 2 yaml:
```yaml
type: entities
entities:
  - entity: binary_sensor.pi_x_haustur_status
    type: custom:multiple-entity-row
    name: Status
    entities:
      - entity: switch.pi_x_haustur_auf
        icon: true
        name: false
        state_color: true
        tap_action:
          action: toggle
          confirmation:
            text: Soll die Haustür entriegelt werden?
title: Haustür
state_color: true
```

Could it be because the main row entity ("_binary_sensor.pi_x_haupttor_geschlossen_") of card 1 is a "**garage_door**" as device_class and the main row entity ("_binary_sensor.pi_x_haustur_status_") of card 2 is a "**connectivity**" as device_class?
