### ISSUE TITLE
Does "hide_if" support null value?

### ISSUE THREAD

**Issue by reefland** [benct/lovelace-multiple-entity-row#226]
I have a `sensor.holiday_name` which value is normally set to empty string.  If it matches a specific date, it will have a non empty string (name of a holiday, birthday, etc).  I'm trying to hide the entity when the value is an empty string, this does not work:

```
      - entity: sensor.holiday_name
        hide_if:
          value:
            - null
        type: custom:multiple-entity-row
        secondary_info: Holiday Lighting Tonight!
```
When I try to define an empty string using two single quotes or two double quotes  it automatically becomes `null` and some languages `null` is not the same as empty sting.

I've tried simpler forms like `hide_if: null` same results, it's not hidden.  I'm wondering if the `null` value is a problem.

**Comment by ildar170975** [comment]
Same as here - https://github.com/benct/lovelace-multiple-entity-row/issues/227

**Comment by reefland** [comment]
Thanks for the reply, I left a comment in that issue.   Your explanation help me come up with an alternate solution.

```
      - entity: binary_sensor.holiday_on
        type: custom:multiple-entity-row
        name: Special Light Colors
        secondary_info:
          entity: sensor.holiday_name
          hide_if: ''
```
