### ISSUE TITLE
hide_if not working

### ISSUE THREAD

**Issue by metbril** [benct/lovelace-multiple-entity-row#227]
I have this card, where `hide_if` doesn't do anything:

```yaml
type: entities
entities:
  - entity: sun.sun
  - entity: sun.sun
    type: custom:multiple-entity-row
    name: Above
    hide_if: below_horizon
  - entity: sun.sun
    type: custom:multiple-entity-row
    name: Below
    hide_if: above_horizon
```

I've tried multiple variants, without effect:

```yaml
  - entity: sun.sun
    type: custom:multiple-entity-row
    name: Below
    hide_if: 
      value: above_horizon

  - entity: sun.sun
    type: custom:multiple-entity-row
    name: Below
    hide_if: 
      value:
        - above_horizon
```

The README doesn't provide examples. Am I doing something wrong?
