### ISSUE TITLE
format relative not working for timestamp attributes

### ISSUE THREAD

**Issue by metbril** [benct/lovelace-multiple-entity-row#229]
I have template sensors that store a timestamp in an attribute and want to show these as secondary info. The last updated attribute is working just fine. The attribute is handled as a string, any `format:` doesn't work

This an example sensor:

```yaml
template:
  - sensor:
      - name: "Example Sensor"
        state: "{{ states('sensor.other_sensor') }}"
        attributes:
          last_known: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0)  }}"
```

This is the example Lovelace:

```yaml
type: entities
entities:
  # not working:
  - entity: sensor.example_sensor
    type: custom:multiple-entity-row
    secondary_info:
      attribute: last_known
      format: relative
  # working:
  - entity: sensor.example_sensor
    type: custom:multiple-entity-row
    secondary_info:
      attribute: last-updated
      format: relative
```

**Comment by metbril** [comment]
Additionally, in the developer tools, I can use this:

```yaml
{% set last_known = state_attr('sensor.example_sensor','last_known') %}
{{ relative_time( last_known ) }}
{{ relative_time( last_known | as_datetime ) }}
```

The first one produces the same results as the secondary_info `format: relative`. The second one is working as expected.

**Comment by ildar170975** [comment]
Probably same: https://github.com/benct/lovelace-multiple-entity-row/issues/221

**Comment by metbril** [comment]
> Probably same: #221

I'm not sure. If I use the `last-updated` special field as secondary info, than it's working just fine (see my second example above).

**Comment by ildar170975** [comment]
> If I use the `last-updated` special field as secondary info, than it's working just fine (see my second example above).

If you change format to smth different, it will not change - it is always "relative".
I agree that all these issues may be related.

**Comment by benct** [comment]
I'm guessing your last_known template attribute gets some weird formatting which the default formatters can't handle.. You could try converting it to a datetime as you do in your working example? Something like
```
last_known: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) | as_datetime }}"
```

**Comment by ildar170975** [comment]
Seems OK for attributes (not `last_changed` & `last_updated`):
```
      - type: custom:multiple-entity-row
        entity: device_tracker.life360_ildar_iphone_5s
        entities:
          - attribute: last_seen
            name: time
            format: time
          - attribute: last_seen
            name: datetime
            format: datetime
          - attribute: last_seen
            name: total
            format: total
          - attribute: last_seen
            name: relative
            format: relative
        show_state: false
```
![image](https://user-images.githubusercontent.com/71872483/154163351-2af6cef7-4e1e-4dad-9310-0a341a072ae3.png)
