### ISSUE TITLE
allow use of entity in the multiple entity row

### ISSUE THREAD

**Issue by Mariusthvdb** [benct/lovelace-multiple-entity-row#23]
HI, 

please consider allowing referencing the config entity in the multiple entity rows, (ie when not referencing an outside entity):
```
  - entity: vacuum.vacuum_cleaner
    type: custom:multiple-entity-row
    primary:
      entity: entity
      attribute: battery_level
      name: Battery
      unit: '%'
    secondary:
      entity: entity
      attribute: status
      name: Status
```
or maybe even:

```
  - entity: vacuum.vacuum_cleaner
    type: custom:multiple-entity-row
    primary:
      attribute: battery_level
      name: Battery
      unit: '%'
    secondary:
      attribute: status
      name: Status
```
instead of:
```
  - entity: vacuum.vacuum_cleaner
    type: custom:multiple-entity-row
    primary:
      entity: vacuum.vacuum_cleaner
      attribute: battery_level
      name: Battery
      unit: '%'
    secondary:
      entity: vacuum.vacuum_cleaner
      attribute: status
      name: Status
```

there's no need to keep repeating the entity, if set in the main config. Keep things short and simple.

And, it would make it so much easier to use the card in other cards or templates (like decluttering templates) Maybe even auto entities, though I am not sure that will go...

anyways, 
thanks!
