### ISSUE TITLE
Theme change not being handled

### ISSUE THREAD

**Issue by Th30wl** [benct/lovelace-multiple-entity-row#232]
Using v4.4.1 but I think that this appeared in v4.3.1. If a theme is changed by an automation, card's theme remains the old one until I refresh the page. (I have automations that switch to light/dark theme at sunrise/sunset)

Before automation is triggered:
![image](https://user-images.githubusercontent.com/30597832/151633410-b738e5d5-69dd-4d1f-aae5-107adf20a6cc.png)

After automation is triggered:
![image](https://user-images.githubusercontent.com/30597832/151633101-eca97170-c5ff-48b8-b530-60d63f7881c3.png)

Automation that I use:
```
alias: Light theme at sunrise
trigger:
  - platform: sun
    event: sunrise
condition: []
action:
  - service: frontend.set_theme
    data:
      name: Caule Light Blue
mode: single
```
