### ISSUE TITLE
Remove device name and attribute from view

### ISSUE THREAD

**Issue by GRClark** [benct/lovelace-multiple-entity-row#234]
How can I show this without the device name (hallway motion sensor) and attribute (battery)?

```

type: entities
entities:
  - entity: binary_sensor.hallway_motion_sensor_motion
    type: custom:multiple-entity-row
    name: Entrance
    secondary_info: last-changed
    entities:
      - sensor.hallway_motion_sensor_battery

```

![image](https://user-images.githubusercontent.com/5118059/153690691-40650a68-8431-4d6f-a161-5d59e3951492.jpeg)
