### ISSUE TITLE
Toggle does not show real state

### ISSUE THREAD

**Issue by loeffelpan** [benct/lovelace-multiple-entity-row#236]
I use your `toggle` option just to display an boolean entity/attribute.
But the toggle does not show proper state of that attribute. Do you have any suggestion how to solve this?

![image](https://user-images.githubusercontent.com/34661317/154229695-73a0faf2-1cdf-457a-9a51-1bd8f7a3fb07.png)

```
type: entities
entities:
  - entity: switch.superb_iv_departure_timer_1
    name: Aktiv
  - type: custom:multiple-entity-row
    entity: switch.superb_iv_departure_timer_1
    attribute: timerProgrammedStatus
    name: Status
  - type: divider
  - type: conditional
    conditions:
      - entity: binary_sensor.abreiseplanung_1_wiederkehrend
        state: 'off'
    row:
      type: custom:multiple-entity-row
      entity: switch.superb_iv_departure_timer_1
      attribute: departureDateTime
      name: Datum und Zeit
      format: datetime
  - type: conditional
    conditions:
      - entity: binary_sensor.abreiseplanung_1_wiederkehrend
        state: 'on'
    row:
      type: custom:multiple-entity-row
      entity: switch.superb_iv_departure_timer_1
      attribute: departureTimeOfDay
      name: Zeit
  - type: conditional
    conditions:
      - entity: binary_sensor.abreiseplanung_1_wiederkehrend
        state: 'on'
    row:
      type: custom:multiple-entity-row
      entity: switch.superb_iv_departure_timer_1
      attribute: departureWeekdayMask
      name: Wochentag(e)
  - type: custom:multiple-entity-row
    entity: binary_sensor.abreiseplanung_1_wiederkehrend
    name: Wiederholend
    toggle: true
  - type: divider
  - type: custom:multiple-entity-row
    entity: switch.superb_iv_departure_timer_1
    attribute: operationCharging
    name: Laden
    toggle: true
  - type: custom:multiple-entity-row
    entity: switch.superb_iv_departure_timer_1
    attribute: targetChargeLevel
    unit: '%'
    name: Ladeziel
  - type: custom:multiple-entity-row
    entity: switch.superb_iv_departure_timer_1
    attribute: chargeMaxCurrent
    name: Ladestrom
  - type: divider
  - type: custom:multiple-entity-row
    entity: switch.superb_iv_departure_timer_1
    attribute: operationClimatisation
    name: Klimatisieren
    toggle: true
  - type: custom:multiple-entity-row
    entity: switch.superb_iv_departure_timer_1
    attribute: heaterSource
    name: Wärmequelle
show_header_toggle: false
state_color: true
title: Abreiseplanung 1
```
