### ISSUE TITLE
Secondary Info translation / localization handling

### ISSUE THREAD

**Issue by FragMenthor** [benct/lovelace-multiple-entity-row#238]
Hello.
I use A LOT the multiple-entity-row, but there is one situation that it does not seem to handle: localization / translation of sensor values. This would be most useful, and I post an example:

```
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: sensor.cave_temperatura_aparente
    name: Conforto
    state_header: T. Aparente
    icon: mdi:thermometer-lines
    entities:
      - entity: sensor.cave_heatindex
        name: Índ. Calor
    secondary_info:
      entity: sensor.cave_perception
  - entity: sensor.cave_perception
```

This sensor ( 'sensor.cave_perception'), when used in an entities card as an entity, has localization / translation, but when used in a multiple-entity-row as secondary info, loses this localization:

![image](https://user-images.githubusercontent.com/74264069/154535544-0d189655-c046-435c-a45e-0436f8945873.png)

Is it possible to implement this, or get the tranlated value in some other way?

Thanks for all this!!! Congratulations :)
