### ISSUE TITLE
Toggle/TapActionToggle not working in Home Assistant 2022.2.9

### ISSUE THREAD

**Issue by fusionstream** [benct/lovelace-multiple-entity-row#239]
Previously, setting `toggle: true` would allow one to toggle a title_icon.

Now, this no longer works. Additionally, manually setting `tap_action: toggle` also does not work

**Comment by ildar170975** [comment]
Defining the "toggle" option has a sense for `input_boolean`, `switch`.
Examples for `input_boolean` are below.

If "toggle an icon" means "change an icon's color" - then I do NOT confirm the issue:
```
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: input_boolean.test_boolean
    entities:
      - entity: sun.sun
      - entity: sun.sun
    show_state: true
    toggle: true
    state_color: true
```
![изображение](https://user-images.githubusercontent.com/71872483/154813137-07444b5a-920c-4372-8346-1cf2d8927670.png)
![изображение](https://user-images.githubusercontent.com/71872483/154813142-e3172226-35e0-4c84-8e62-14b945d13f18.png)

If "toggle an icon" means "change an icon" - then it depends on whether an `icon` option was defined for this `input_boolean` entity. The `input_boolean.test_boolean` has a specified `mdi:car` icon - so the icon is not changed when the entity is toggled.
If the `icon` option is NOT defined - then the icon is changed when toggled:
```
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: input_boolean.notification_flag_net_warning
    entities:
      - entity: sun.sun
      - entity: sun.sun
    show_state: true
    toggle: true
    state_color: true
```
![изображение](https://user-images.githubusercontent.com/71872483/154813385-09e16bbd-e117-4b23-8470-97988af3d8d4.png)
![изображение](https://user-images.githubusercontent.com/71872483/154813376-d6f986f2-8a3d-44fc-bdf9-3b71f55eae64.png)

Close the issue if it is solved.

**Comment by fusionstream** [comment]
No. I mean clicking on a multiple-entity entity in a layout of title_icon does not toggle the entity itself
![Image 001](https://user-images.githubusercontent.com/3389188/154854349-7fe3c098-f630-4a83-b746-2a935cfe0d15.png)

Instead it pops up a more-info dialog
![Image 002](https://user-images.githubusercontent.com/3389188/154854367-9df474aa-d342-4f7c-a21d-9f52dfb03110.png)

From where you can then toggle the entity
![Image 003](https://user-images.githubusercontent.com/3389188/154854377-60672efa-4418-4671-95c0-a5bb2dd004f5.png)

Previously, the multiple-entity entity was toggleable simply by clicking on it (if `toggle: true`). No more-info dialog was produced.

```
- entity: light.wled
  name: TV
  secondary_info: brightness
  type: custom:multiple-entity-row
  toggle: true
  entities:
    - entity: input_boolean.toggle_tv_follow_source
      name: Follow Source
      icon: mdi:import
      toggle: true
      state_color: true
    - entity: input_boolean.toggle_tv_follow_console_backlight
      name: Auto On
      icon: mdi:lightbulb-auto
      toggle: true
      state_color: true
```

No yaml was changed after upgrading to Home Assistant 2022.2.9

**Comment by ildar170975** [comment]
In the docs:
![изображение](https://user-images.githubusercontent.com/71872483/154861631-6c9fcf2c-36df-4f3a-bc7e-4f52faada59b.png)

Example:
```
type: entities
entities:
  - entity: input_boolean.test_boolean
  - entity: input_boolean.test_boolean_2
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - entity: input_boolean.test_boolean
        toggle: true
      - entity: input_boolean.test_boolean_2
        toggle: true
```
![изображение](https://user-images.githubusercontent.com/71872483/154861611-da674e93-2188-476d-8eab-8e094937ada0.png)

The toggle is displayed and clicking on it toggles an entity.

Adding an icon DO NOT show a toggle:
```
      - entity: input_boolean.test_boolean
        icon: mdi:car
        toggle: true
```
![изображение](https://user-images.githubusercontent.com/71872483/154861726-6646e04d-a996-4752-8395-e6006cd54197.png)
There is no button to toggle.

Are you sure that earlier you could combine `toggle: true` with some icon?
For me it seems to be two different things.

You may specify a `toggle` action for the icon:
```
      - entity: input_boolean.test_boolean
        icon: mdi:car
        tap_action:
          action: toggle
        state_color: true
```
![изображение](https://user-images.githubusercontent.com/71872483/154861876-70b44fcf-6494-478d-a268-2419a1060515.png)

**Comment by fusionstream** [comment]
> Are you sure that earlier you could combine toggle: true with some icon?

Yup. Yaml was unchanged. I chose this over:

```
tap_action:
  action: toggle
```
specifically because it worked and had better readability.

In my haste to fix this sudden issue though I did miss the fact that the documented method is 
```
tap_action:
  action: toggle
```
and not
```
tap_action: toggle
```

Therefore I will be closing this issue. Thank you for your assistance.

**Comment by loeffelpan** [comment]
Just got a similar situation and found your issue.
But your issue seems to be solved with
```
tap_action:
  action: toggle
```

I have this row with template-switches for every weekday.
```
      type: custom:multiple-entity-row
      entity: input_text.deptimer_days
      name: Wochentage
      show_state: false
      entities:
        - entity: switch.deptimer_mon
          name: Mo
          state_color: true
          icon: mdi:calendar
          tap_action:
            action: call-service
            service: switch.toggle
            service_data:
              entity_id: switch.deptimer_mon
        - entity: switch.deptimer_tue
          name: Di
          icon: mdi:calendar
          state_color: true
          tap_action:
            action: toggle
        - entity: switch.deptimer_wed
          name: Mi
          icon: mdi:calendar
          state_color: true
        - entity: switch.deptimer_thu
          name: Do
          icon: mdi:calendar
          state_color: true
        - entity: switch.deptimer_fri
          name: Fr
          icon: mdi:calendar
          state_color: true
        - entity: switch.deptimer_sat
          name: Sa
          icon: mdi:calendar
          state_color: true
        - entity: switch.deptimer_sun
          name: So
          icon: mdi:calendar
          state_color: true
```

First one works. Second (like yours) does nothing.
Third and all others shows `more-info`-dialog, despite a switch should be togglable.

**Comment by ildar170975** [comment]
> despite a switch should be togglable.

Already explained above, you are asking absolutely same question.
Since you provided an icon - the items is NOT toggleable.

This code works fine since you specified `tap_action`:
```
      - entity: switch.test_switch
        name: Mo
        state_color: true
        icon: mdi:calendar
        tap_action:
          action: call-service
          service: switch.toggle
          service_data:
            entity_id: switch.test_switch
```
as well as here:
```
      - entity: switch.test_switch
        name: Di
        icon: mdi:calendar
        state_color: true
        tap_action:
          action: toggle
```
But this code will allow you "toggle by tapping":
```
      - entity: switch.test_switch
        name: Mi
        icon: mdi:calendar
        state_color: true
```
as well as this:
```
      - entity: switch.test_switch
        name: Mi
        icon: mdi:calendar
        state_color: true
        toggle: true
```

This code will work:
```
      - entity: switch.test_switch
        name: Mi
        state_color: true
        toggle: true
```

**Comment by loeffelpan** [comment]
> as well as here:
> ```
>       - entity: switch.test_switch
>         name: Di
>         icon: mdi:calendar
>         state_color: true
>         tap_action:
>           action: toggle
> ```

Sorry for  missing that.
Would be fine if that one above would work.
But it doesn't. Tapping does nothing. Thats why I'm commenting this issue.

**Comment by ildar170975** [comment]
```
type: entities
entities:
  - entity: switch.test_switch
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - entity: switch.test_switch
        name: Di
        icon: mdi:calendar
        state_color: true
        tap_action:
          action: toggle
```
![Untitled Projectaaaa](https://user-images.githubusercontent.com/71872483/155207762-b70f1f70-0c22-4f59-bfdc-a17fe545b305.gif)
