### ISSUE TITLE
Use hide_if on icon based on a different entity (ie.: show low battery icon on motion sensor)

### ISSUE THREAD

**Issue by alexruffell** [benct/lovelace-multiple-entity-row#245]
It would be awesome if one could make a low battery icon appear next to the state of a battery operated device only when the battery is below a certain threshold. Below is an example of what I am proposing:
```
  - entity: binary_sensor.front_porch_motion_sensor
    type: custom:multiple-entity-row
    entities:
      - icon: mdi:battery-low
        styles:
          --paper-item-icon-color: red
        hide_if:
          entity: sensor.front_porch_motion_sensor_battery
          above: 35
```
![image](https://user-images.githubusercontent.com/4006944/160193059-f0d72f03-753a-4361-ac77-c60057875783.png)

I've spent hours trying to hack my way to this but failed. Direct support in `custom:multiple-entity-row` would eliminate the need to go with complicated solutions as card-mod (which did not work for me).

**Comment by ildar170975** [comment]
Imho these kind of questions are better to ask in the Community and leave Github for bugs & FRs.

**Comment by alexruffell** [comment]
This was not meant to be a bug report but an **enhancement request.** @ildar170975 I believe you helped me accomplish this using card-mod but the code is lengthy and complex compared to using what I suggested above. Since the custom card already has the feature to `hide_if` other elements, it would be a matter of extending that to icon as well.

**Comment by ildar170975** [comment]
> it would be a matter of extending that to icon as well.

I see your point. But:
1) To add the `hide_if ` option for the "just an icon w/o entity" an additional "entity" option should be added to the "[Hiding](https://github.com/benct/lovelace-multiple-entity-row#hiding)" options.
2) Currently the "Hiding" options include only "above" & "below". If someone needs a bit different logic or use it for non-numeric values - then these "Hiding" options cannot help.

As you can see the "Hiding" options have limited applications. I guess these options were added to cover some most common (or most popular) needs. For other cases we have to use config-template-card or card-mod.

I am not saying that your issue is somehow wrong - I just want to say that your case (and more complex) cases can be solved by other methods.

**Comment by alexruffell** [comment]
You, or someone with your same first name helped me achieve what I wanted to do. Comparing the code he provided with what I had tried it is clear I have no idea what I am doing :) The code below works. Sharing it here just in case others need it.

```
  - type: custom:multiple-entity-row
    entity: binary_sensor.front_porch_motion_sensor
    entities:
      - entity: sensor.front_porch_motion_sensor_battery
        name: false
        format: precision0
        hide_if:
          above: 35
      - icon: mdi:battery-alert-variant-outline
        entity: sensor.front_porch_motion_sensor_battery
        name: false
        format: precision0
        hide_if:
          above: 35
        styles:
          '--paper-item-icon-color': red
    show_state: true
```
