### ISSUE TITLE
Formatting relative doesn't work

### ISSUE THREAD

**Issue by loeffelpan** [benct/lovelace-multiple-entity-row#246]
I got a sensor with device_class `timestamp`.
It looks like this:
![06B60297-A7B5-4A04-AF43-D153F5F1DB83](https://user-images.githubusercontent.com/34661317/162803519-31c35418-bc70-4bf6-a2ea-198de042bbaa.jpeg)

I'm trying to use this as secondary info and format it as relative time.
```
  - type: custom:multiple-entity-row
    entity: sensor.superb_iv_last_trip_average_electric_consumption
    name: Letzte Fahrt
    icon: mdi:map-marker-distance
    state_header: kWh/100km
    unit: false
    secondary_info:
      entity: sensor.superb_iv_parking_time
      format: relative
      name: false
```

But it doesn't show relative time.
![CB5CB658-B788-4454-BC9B-970B508DF645](https://user-images.githubusercontent.com/34661317/162804178-63f6f418-82f1-4734-b16d-135349ae47fc.jpeg)
