### ISSUE TITLE
FR: Substitution text for a state

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#247]
It could be great to have a possibility to substitute a sensor's state value by some user-defined text.
Particularly it could be useful to write smth like "No data" instead of "Unavailable" - if the sensor is unavailable:
```
  - type: entities
    entities:
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.service_unavailable_value
        show_state: false
```
![image](https://user-images.githubusercontent.com/71872483/162852385-c8e56d9c-852f-425d-9342-4042f124e0e4.png)

Another example is to write "cool", "hot", "warm" instead of writing an actual temperature.

To implement this functionality, I propose to add a new option - `substitute_if`.
This option should be available:
- for the main entity;
- for each additional entities.

The option should be an object like a "hide_if" option.
Below there is a draft of the paragraph from ReadMe:
```
### Substitution

The `substitute_if` option can be used to substitute an entity's state if its state or attribute value matches the specified criteria.
It can be used directly with a string, number or boolean value (i.e. `substitute_if: 'off'`), as a list with several values,
or as an object with one or more of the options listed below.

| Name    | Type     | Description                                                         |
| ------- | -------- | ------------------------------------------------------------------- |
| text    | string   | Substitution text                                                   |
| above   | number   | Substitute if entity _number_ value is above the specified value    |
| below   | number   | Substitute if entity _number_ value is below the specified value    |
| value   | list/any | Substitute if value matches specified value or any value in a list  |
```
