### ISSUE TITLE
Overriding entity for more-info action not working

### ISSUE THREAD

**Issue by kaizersoje** [benct/lovelace-multiple-entity-row#251]
I have the code below where I have defined 2 `more-info` actions.

```yaml
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: sensor.daily_grid_consumption
    name: Daily
    format: precision1
    state_header: Grid
    double_tap_action:
      action: more-info
    tap_action:
      action: more-info
      entity: sensor.pv_eday
    entities:
      - entity: sensor.pv_eday
        name: Solar
    secondary_info:
      entity: sensor.date
      name: false
```

I have noticed that both actions are showing the info dialog box for the same entity. The `tap_action`  is not using the `entity` defined in the configuration.
