### ISSUE TITLE
Date entities/attributes not using the format in iOS devices

### ISSUE THREAD

**Issue by kaizersoje** [benct/lovelace-multiple-entity-row#252]
I have noticed that an entity where the attribute format is set to `relative` is not being displayed correctly on iOS devices.

This is how it is displayed on an Android device.
![Android2](https://user-images.githubusercontent.com/54566217/168281167-c7b2a3f8-59e9-4d64-8f79-acf447f0f261.png)

This is how it is displayed on an iOS device.
![iOS2](https://user-images.githubusercontent.com/54566217/168281164-2f4453fa-c4d7-4e65-b852-d19962d58df2.jpeg)

This is the code.

```yaml
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: sensor.pv_output_power
    name: Solar PV
    icon: mdi:solar-power
    name_state: Current
    format: kilo
    unit: kW
    double_tap_action:
      action: more-info
      entity: sensor.inverter_none
    secondary_info:
      entity: sensor.sems_portal_status
      attribute: updated_date
      format: relative
      name: false
    entities:
      - entity: sensor.pv_temperature
        name: Temp
        format: precision0
      - entity: sensor.elevation
        name: Sun
```
