### ISSUE TITLE
Clicking the sub-entity on mobile opens the wrong entity

### ISSUE THREAD

**Issue by davidlang42** [benct/lovelace-multiple-entity-row#253]
In a full size browser/ PC, clicking the sub-entity value opens the entity details for the sub-entity
=> This is the desired behaviour

In a mobile browser (or the mobile app), clicking the sub-entity value open the entity details for the main entity
=> This is incorrect.

This is reproducable with the following YAML configuration for lovelace card:
```
entities:
  - entity: sensor.downstairs_temperature
    type: custom:multiple-entity-row
    name: Downstairs
    secondary_info:
      entity: sensor.downstairs_battery
      name: 🔋
    entities:
      - entity: sensor.downstairs_humidity
        name: humidity
```
1. Open HA in Chrome on Android, or the Android HomeAssistant app
2. Click the humidity value
Expected: entity details for sensor.downstairs_humidity
Actual: entity details for sensor.downstairs_temperature

**Comment by mattthewclayton** [comment]
Hey, thanks for opening this issue, it was on my todo list to raise. I got a slap on the wrist for commenting on a closed ticket but it does look incredibly similar (in symptoms) to this issue: https://github.com/benct/lovelace-multiple-entity-row/issues/217 

There is a comment in that thread that they gave up looking at iOS because it seemed too buggy, someone was asked to raise a ticket for iOS in December but I could not find one.

I can confirm if I remove my "tap_action" blocks from my example, I get the same behaviour as you David the more info of the main entity is shown in iOS but it works as expected on web.

Are you also using iOS @davidlang42 ?

**Re-posting my comment from the other ticket:** 

In order for the tap_action to work on the entity (not the row) I have to do a long (3D?) press, and even then it's fairly intermittent if it works, you have to be very precise with your finger it seems.

Is this likely an issue with this integration or with the iOS companion app?

HA Version: 2022.5.0
Companion App: 2022.3

![Untitled](https://user-images.githubusercontent.com/9895197/169512112-b7ca84b2-3031-41ad-bce3-fa6e5a448c33.png)
```
entities:
  - entity: climate.living_room
    type: custom:multiple-entity-row
    icon: mdi:temperature-celsius
    secondary_info:
      attribute: current_temperature
      unit: °C
    name: Living
    tap_action: none
    show_state: false
    entities:
      - entity: light.living_room
        icon: mdi:ceiling-light
        name: Living
        tap_action:
          action: toggle
      - entity: light.dining_room
        icon: mdi:ceiling-light
        name: Dining
        tap_action:
          action: toggle
      - entity: light.kitchen
        icon: mdi:ceiling-light
        name: Kitchen
        tap_action:
          action: toggle
      - entity: switch.left_lamp
        icon: mdi:lamp
        name: Left
        tap_action:
          action: toggle
      - entity: switch.right_lamp
        icon: mdi:lamp
        name: Right
        tap_action:
          action: toggle
```
