### ISSUE TITLE
Some way to use jinja or template operations?

### ISSUE THREAD

**Issue by daytonturner** [benct/lovelace-multiple-entity-row#254]
From what I gather, there's no way to use jinja or other template operations within this card, but hopefully someone has an idea of how I could accomplish this?

I have a card like:

```
entity: sensor.bc_ferries_langdale_to_horseshoe_bay_schedule_1
type: custom:multiple-entity-row
name: Next Ferry
show_state: false
icon: mdi:ferry
entities:
  - attribute: time
    name: Time
  - attribute: carFill
    name: Full
    unit: '%'
```

It displays two attributes from my sensor, "time" and "carFill" which is great.

I've got another sensor, a google maps transit time, that I've built a jinja template around, to take the "time" attribute from this sensor, and subtract travel time from it, leaving me with a "Time to leave", basically.

Problem is, I cant figure out a way to include jinja to do the timestamp offset calculations in the entities list.

Can anyone think of a way i might do this?
