### ISSUE TITLE
issue with color being active for non-active switches

### ISSUE THREAD

**Issue by alamoudimoh** [benct/lovelace-multiple-entity-row#260]
Hi, i would like to be able to have the color active only for the active icon, not everything, as of the below code, once any of the 3 switches are active, it will show the entire switches as active

```
type: entities
entities:
  - entity: switch.master_switch_01
    type: custom:multiple-entity-row
    name: Master Switch 01
    icon: mdi:lightbulb-outline
    tap_action:
      action: call-service
      service: switch.toggle
      service_data:
        entity_id: switch.master_switch_01
    toggle: true
    state_color: true
    entities:
      - icon: mdi:lightbulb-outline
        state_color: true
        name: 1
        tap_action:
          action: call-service
          service: switch.toggle
          service_data:
            entity_id: switch.master_switch_01_right
      - icon: mdi:lightbulb-outline
        state_color: true
        name: 2
        tap_action:
          action: call-service
          service: switch.toggle
          service_data:
            entity_id: switch.master_switch_01_center
      - icon: mdi:lightbulb-outline
        state_color: true
        name: 3
        tap_action:
          action: call-service
          service: switch.toggle
          service_data:
            entity_id: switch.master_switch_01_left
```
