### ISSUE TITLE
Confirmation Option ignored if Toggle is set to true

### ISSUE THREAD

**Issue by gmarlow** [benct/lovelace-multiple-entity-row#265]
If an entity has an attribute of toggle: true, the confirmation attribute is ignored.

**Comment by ildar170975** [comment]
IMHO, for toggles, confirmation is not supposed to popup.
Check this conventional Entities card:
```
type: entities
entities:
  - entity: input_boolean.test_boolean
    tap_action:
      action: toggle
      confirmation:
        text: Are you sure?
```
The confirmation is requested only when tapping on the icon or name.
