### ISSUE TITLE
Confirmation popups look differently

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#266]
Consider this example:
```
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: input_boolean.test_boolean
    tap_action: &ref_action
      action: toggle
      confirmation:
        text: Are you sure?
    entities:
      - icon: mdi:account
        tap_action: *ref_action
```
![изображение](https://user-images.githubusercontent.com/71872483/190196236-85f41af3-241d-43cd-ad65-b56c5393b5f1.png)

The card has same `input_boolean` entity in 2 places.
For both places a `"tap_action"` with confirmation popup is specified.

Tapping on the left side (icon, name) causes displaying this confirmation popup:
![изображение](https://user-images.githubusercontent.com/71872483/190196920-71c20954-e26a-4ed4-9251-a3f35714cf58.png)

Tapping on the icon shows a differently looking & placed popup:
![изображение](https://user-images.githubusercontent.com/71872483/190197373-46d0f17e-9771-4e0c-b8e4-d40459cf3b8a.png)
