### ISSUE TITLE
Custom element doesn't exist: multiple-entity-row

### ISSUE THREAD

**Issue by antgustech** [benct/lovelace-multiple-entity-row#277]
This is what I did:

Located my configuration folder. Sadly it did not contain a directory named www so I created one and downloaded the latest script. I den edited my configuration.yml with
```
lovelace:
  resources:
    - url: /local/multiple-entity-row.js?v=4.4.1
      type: module
```

Restarted HA and added a new card with the following code:

```
type: entities
entities:
  - entity: sensor.aqara_temp_2_2
    type: custom:multiple-entity-row
    name: Vardagsrum
    secondary_info: last-changed
    entities:
      - entity: sensor.aqara_temp_2_2
        name: Temp
      - entity: sensor.aqara_temp_2
        name: Luftfuktighet
```
However when I save, it says that the type cannot be found:

Custom element doesn't exist: multiple-entity-row

What did I do wrong here?
