### ISSUE TITLE
Unit field ignored in secondary_info

### ISSUE THREAD

**Issue by lbandi2** [benct/lovelace-multiple-entity-row#282]
I've tried many combinations before opening this issue. The problem is that I can't seem to make the unit of measurement show in secondary info:

```
      - entity: sensor.fridge_consumption
        type: custom:multiple-entity-row
        secondary_info:
          entity: sensor.fridge_consumption
          unit: "Watts"

```

The `unit` field get's completely ignored, the result is I get the value in secondary info but no unit of measurement. Not only it ignores the one I provide, but it also ignores the original unit of the sensor.

I've tried this in another case by adding another entity and it shows the unit of measurement no problem:

```
      - entity: sensor.fridge_consumption
        type: custom:multiple-entity-row
        secondary_info:
          entity: sensor.fridge_consumption
          unit: "Watts"
        entities:
          - entity: sensor.fridge_consumption
            unit: "Watts"

```

Am I doing something wrong? Per the documentation I think it should work.

**Comment by ildar170975** [comment]
@lbandi2 
Do you still see the issue?
Asking 'cause I do not confirm:

![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/34f03c26-be61-4822-9249-dd8b619c7182)

```
type: entities
entities:

  - type: custom:multiple-entity-row
    entity: sensor.processor_use
    secondary_info:
      entity: sensor.xiaomi_cg_1_co2
      unit: "Watts"

  - type: custom:multiple-entity-row
    entity: sensor.processor_use
    secondary_info:
      entity: sensor.processor_use
      unit: "Watts"
```
