### ISSUE TITLE
Can't hide or rename sub-entity names

### ISSUE THREAD

**Issue by JohnBull-1975** [benct/lovelace-multiple-entity-row#284]
Trying with this example

  - type: section
  - entity: sensor.bedroom_temperature
    type: custom:multiple-entity-row
    name: Hide headers (name)
    entities:
      - entity: sensor.bedroom_min_temp
        name: false
      - entity: sensor.bedroom_max_temp
        name: false

Without "name: false" it works fine, but I get a long header name for both entities

If I do like this, the value for sub-value sensor.forrad_trh_temperature dissapear
type: entities
entities:
  - entity: sensor.forrad_trh_temperature
    type: custom:multiple-entity-row
    name: Förråd
    secondary_info: last-changed
    entities:
      - sensor.forrad_trh_temperature
        name
      - sensor.forrad_trh_humidity

If I write a colon after name
name:
I get:
_Configuration errors detected:
bad indentation of a sequence entry (9:13)

  6 |     secondary_info: last-changed
  7 |     entities:
  8 |       - sensor.forrad_trh_temperature
  9 |         name:
------------------^
 10 |       - sensor.forrad_trh_humidity
 11 |_ 

If I type a character right after name: it is accepted, but sensor value dissapear
If I try with a space after name: it complaint about configuration again

Otherwise this card-tool looks exactly what I have been searching for!

**Comment by ildar170975** [comment]
The code you posted cannot be used for analysis since it is not formatted as a code.
Use triple "`".

As for the problem - check this:
```
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - entity: sun.sun
        name: false
      - entity: sun.sun
        name: any name
      - entity: sun.sun
```

**Comment by JohnBull-1975** [comment]
OK...new to this...new attempt:

This doesn't work

```
type: entities
type: entities
entities:
  - entity: sensor.forrad_trh_temperature
    type: custom:multiple-entity-row
    name: Förråd
    secondary_info: last-changed
    entities:
      - sensor.forrad_trh_temperature
        name: false
      - sensor.forrad_trh_humidity
	 
```
![image](https://user-images.githubusercontent.com/121295714/215862628-afb9398b-6b17-4b2d-a6c8-c1b43133c021.png)

If I remove the name-row, then it works fine

![image](https://user-images.githubusercontent.com/121295714/215862535-72ec1fcd-41c0-456b-8d2f-8893eee5abda.png)

Thanks for trying to help!
