### ISSUE TITLE
Sensor precision not respected

### ISSUE THREAD

**Issue by Wesley-Vos** [benct/lovelace-multiple-entity-row#286]
The new sensor precision introduced in 2023.3.0 is not respected. The full sensor value is shown instead of the rounded value.

You can reproduce it by adding a multiple-entity-row with a numeric sensor entity. In the more-info dialog of the sensor, change the precision to something non-default and observe that the full state is still shown in the multiple-entity-row.

For more information, see https://developers.home-assistant.io/blog/2023/02/08/sensor_presentation_rounding/

**Comment by TheQue42** [comment]
@Wesley-Vos : Trying to understand your Edit.... (since I dont have a clue how these js-plugins are coded) have you got a workaround for the issue?
(I am a bit worried that this repo isnt that active?)

**Comment by Wesley-Vos** [comment]
> @Wesley-Vos : Trying to understand your Edit.... (since I dont have a clue how these js-plugins are coded) have you got a workaround for the issue?
> 
> (I am a bit worried that this repo isnt that active?)

You have to add it to your card configuration in HA, not in the plug-in itself luckily.

For example, check out this card configuration:
```yaml
type: entities
entities:
  - entity: sensor.util_energy_daily
    name: Usage today
    secondary_info: last-updated
    show_state: false
    type: custom:multiple-entity-row
    entities:
      - entity: sensor.util_energy_daily_low
        name: Low
        format: precision2
      - entity: sensor.util_energy_daily_high
        name: High
        format: precision2
      - entity: sensor.util_energy_daily
        name: Total
        format: precision2
```
The `format: precision2` is the additional option I meant. This will do the rounding for now, until it is fixed.
