### ISSUE TITLE
Card broken in 2023.4

### ISSUE THREAD

**Issue by w1tw0lf** [benct/lovelace-multiple-entity-row#288]
Not  displaying secondary info

![image](https://user-images.githubusercontent.com/55384762/230344470-43a59ff8-e98e-45bc-8ff4-da998c514e4e.png)

**Comment by ildar170975** [comment]
You provided ZERO info regarding your case - no code, no info about real values for the displayed data.

I do not see any NEW issues with secinfo:
```
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - entity: sun.sun
        attribute: elevation
        name: elev.
    show_state: true
    secondary_info: last-changed
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - entity: sun.sun
    show_state: false
    secondary_info:
      entity: zone.home
```
![image](https://user-images.githubusercontent.com/71872483/230357717-9387701e-0ba0-4b9d-a3fe-886bc8fda4af.png)

There are other old issues, they are documented on Github.

**Comment by w1tw0lf** [comment]
Here is the code incase it helps
```
    type: horizontal-stack
    cards:
      - type: entities
        entities:
          - type: custom:multiple-entity-row
            entity: sensor.unifi_48port
            name: 48 Port Switch
            show_entity_picture: true
            show_state: false
            secondary_info:
              attribute: Uptime
            entities:
              - entity: sensor.unifi_48port_cpu
                name: CPU
              - entity: sensor.unifi_48port_ram
                name: RAM
              - icon: mdi:restart
                tap_action:
                  action: call-service
                  confirmation: true
                  service: shell_command.reboot_unifi_48port
          - type: custom:multiple-entity-row
            entity: sensor.unifi_48port
            icon: mdi:devices
            name: ' '
            show_state: false
            secondary_info:
              entity: sensor.unifi_48port
              name: ' '
            entities:
              - entity: sensor.unifi_48port_users
                name: Users
              - entity: sensor.unifi_48port_guests
                name: Guests
```

Was working 100% up untill update to 2023.4
![image](https://user-images.githubusercontent.com/55384762/230367159-4e4c2239-051b-4a28-a359-096b0e6925a4.png)

PS: screenshot is from whe the switch was still a 24 port, but code is the same.
