### ISSUE TITLE
Entity States missing after Upgrade HA 2023.4.1

### ISSUE THREAD

**Issue by nireins** [benct/lovelace-multiple-entity-row#289]
Hi, after upgrade to HA 2023.4.1 the Entity States are missing, see screenshot below:

![grafik](https://user-images.githubusercontent.com/69728116/230751451-15652d42-e4f7-4234-802a-609a1041cbf3.png)

This is my Code:

square: false
columns: 1
type: grid
cards:
  - type: entities
    entities:
      - entity: >-
          sensor.siemens_ti9575x1de_68a40e256c81_bsh_common_status_operationstate
        name: Status
        icon: mdi:coffee-maker
      - entity: sensor.401030425339002116_bsh_common_option_programprogress
        type: custom:multiple-entity-row
        name: Status
        icon: mdi:dishwasher
        entities:
          - entity: sensor.401030425339002116_bsh_common_status_operationstate
            name: false
          - entity: sensor.401030425339002116_active_program
            name: false
          - entity: sensor.dishwasher_finish
            name: false

When i create a new Entity Card with the Entity sensor.401030425339002116_bsh_common_status_operationstate the State displayed correct. In my Case "An"; "Aus", "Laufend" -> (translate to english: "On"; "Off"; "Run").

Whats wrong? Can you help me please?

Thanks, greetings

**Comment by Anton-Ka** [comment]
Similar issue:
![image](https://user-images.githubusercontent.com/74901464/231978582-d8d34fd7-fa5b-46f6-9265-52526c00d304.png)
![image](https://user-images.githubusercontent.com/74901464/231978685-8ca88100-84ab-4462-8ba4-4928c5720482.png)
Code:
```
                - entity: binary_sensor.internet_is_available
                  type: custom:multiple-entity-row
                  name: Интернет соединение
                  secondary_info:
                    entity: binary_sensor.internet_is_available
                    name: false
                  show_state: false
```
