### ISSUE TITLE
Icon not in row

### ISSUE THREAD

**Issue by szaman-89** [benct/lovelace-multiple-entity-row#29]
Is it possible to fix icon not in row with other information?
![image](https://user-images.githubusercontent.com/16887051/72477283-72be3180-37ef-11ea-80ce-b77aef9e05a9.png)

**Comment by benct** [comment]
How is your configuration? You need to use multiple-**entity-row** in an [entities](https://www.home-assistant.io/lovelace/entities/) card. 
```
type: entities
entities:
  - entity: sensor.your_sensor_entity
    type: custom:multiple-entity-row
    ...
```
