### ISSUE TITLE
Main entity state is invisible

### ISSUE THREAD

**Issue by wiuwiu** [benct/lovelace-multiple-entity-row#3]
Hi. First of all, thank you for your great job!

I'm trying to figure out where is the problem with showing main entity in my example.
Here is the code:

```
      - entity: sensor.hue_dimmer_child_room_link
        type: custom:multiple-entity-row
        primary:
          entity: sensor.przycisk_u_samuela
          attribute: battery
          name: Bateria
          unit: '%'
```
and this is what I have on UI:
![obraz](https://user-images.githubusercontent.com/21005444/61573525-7a0ab980-aab0-11e9-89a2-ab62b2518c4f.png)

This entity should have "online" state but it's null.

But when I have another entity witch state different than "online" everything works fine.
