### ISSUE TITLE
Display last-changed from other entity

### ISSUE THREAD

**Issue by Pendora2017** [benct/lovelace-multiple-entity-row#30]
Hi there,

i dont know if it's a problem with my understanding of the code but i'm trying to display on info the "last-changed" from another entity.

Backgroundstory: 
The ioBroker Addon "radar2" stores 2 Objects for one device:
![objects](https://user-images.githubusercontent.com/28994273/72557355-d9e7ee80-38a0-11ea-9954-77bfcedf23f3.JPG)

In my custom card i tried the following:
```
type: entity-filter
entities:
  - entity: _.monitoring_device_brotherscanner_here
    type: 'custom:multiple-entity-row'
    name: Brother Scanner
    info:
      entity: _.monitoring_device_brotherscanner_last_here

state_filter:
  - false

card:
  title: Devices offline
  show_header_toggle: false
```

On the info line it shows me the value (timestamp) but i need the last-changed from this object.
How do i do this?

**Comment by benct** [comment]
It is currently only possible to show the `last-changed` property of the main entity. I will have to add specific support for showing last changed for other entities because this property is not treated in the same way as attributes on the entity objects.

However, there is possibly a "work-around" you could try for now:
```
  - entity: _.monitoring_device_brotherscanner_last_here
    type: 'custom:multiple-entity-row'
    name: Brother Scanner
    secondary_info: last-changed
    hide_state: true
    primary:
      entity: _.monitoring_device_brotherscanner_here
      name: false
```
