### ISSUE TITLE
[FR] Add ability to send variables when calling scripts thru tap-action

### ISSUE THREAD

**Issue by larry-glz** [benct/lovelace-multiple-entity-row#300]
I'm trying to run a script via a button on the entity row.  However, it seems variables (fields) are not passed to script via "service-data".  See below:

```
entity: switch.schedule_well_watering_corral
type: custom:multiple-entity-row
name: Corral
secondary_info:
  attribute: weekdays
toggle: true
state_color: true
entities:
  - entity: script.well_watering_program_test
    name: ' '
    icon: mdi:play
    state_color: true
    tap_action:
      action: call-service
      service: script.turn_on
      service_data:
        entity_id: script.well_watering_program_test
        variables:
          watering_runtime: '{{ states(''input_number.well_watering_runtime_corral'') }}'
```

thanks
