### ISSUE TITLE
Using "default" option: a header is only shown when "name" is defined explicitly (+styling lost)

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#302]
Consider this code:
```
type: entities:
entities:
      - type: custom:multiple-entity-row
        entity: sun.sun
        name: 'hide_unavailable: false'
        entities:
          - entity: sensor.testing_availability
        show_state: false

      - type: custom:multiple-entity-row
        entity: sun.sun
        name: 'hide_unavailable: true'
        entities:
          - entity: sensor.testing_availability
            hide_unavailable: true
        show_state: false

      - type: custom:multiple-entity-row
        entity: sun.sun
        name: 'hide_unavailable: true'
        entities:
          - entity: sensor.testing_availability
            hide_unavailable: true
            default: xxx
        show_state: false

      - type: custom:multiple-entity-row
        entity: sun.sun
        name: 'hide_unavailable: true'
        entities:
          - entity: sensor.testing_availability
            hide_unavailable: true
            default: xxx
            name: some_name
        show_state: false
```
where `sensor.testing_availability` is a sensor which may become `unavailable`.
Here the results:

![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/ac0f5bc1-9599-401c-b05f-56d008179018)

![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/b665fcc2-6a35-40a8-bea7-51ee89aaa805)

If the entity is hidden AND `default` is set -> then:
1. If `name` is NOT defined explicitly:
-header is NOT shown
-styling is lost.
2. If `name` is defined explicitly:
-header is shown
-styling IS lost.

IMHO:
1. A header must be displayed if `default` value is displayed (unless it is explicitly hidden by `name: false`).
2. Styling should be persistent.

**Comment by ildar170975** [comment]
Similarly - a `name: false` option does not work:
```
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - entity: sensor.testing_availability
        name: false
        hide_unavailable: true
        default: xxx

      - entity: sensor.testing_availability
        name: some_name
        hide_unavailable: true
        default: yyy

      - entity: sensor.testing_availability
        hide_unavailable: true
        default: zzz

    show_state: false
```
![изображение](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/c4f6f62f-1791-4595-b2fc-47688f37a88a)

![изображение](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/487fd991-eaeb-4c79-bef4-3582539cd5d0)
