### ISSUE TITLE
"invert" formatter: precision is lost

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#304]
There is an `input_number` entity:
![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/74e714fe-1a38-4209-b59c-62ebd5467fae)

Consider this card:
```
  - type: entities
    entities:
      - entity: input_number.test_negative_1
        name: test value

      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: input_number.test_negative_1
            name: unformatted
        show_state: false

      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: input_number.test_negative_1
            name: invert
            format: invert
        show_state: false
```
![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/2ef948b9-1b31-49ce-9d0c-cd09cd39abf2)

The entity has ".xxxx" precision, the inverted value has ".xx" precision.

--------------

Example with a template sensor:
![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/14180ac3-96c5-4778-bc24-916357669750)

```
type: entities
entities:
  - entity: sensor.test_value
    name: test value
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - entity: sensor.test_value
        name: unformatted
    show_state: false
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - entity: sensor.test_value
        name: invert
        format: invert
    show_state: false
```
![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/c89f618f-96a8-4671-a28a-15f8fa3e5287)

Same - precision changed to ".xx".

**Comment by ildar170975** [comment]
Same about `kilo` & `position` formatters:
```
    type: entities
    entities:
      - entity: sensor.test_value
        name: test value
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.test_value
            name: unformatted
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.test_value
            name: kilo
            format: kilo
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.test_value
            name: position
            format: position
        show_state: false
```
![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/7c8f3ce3-7115-4a66-bee3-324bd181e026)
