### ISSUE TITLE
secondary-info: inconsistancy with "last-chaged" & "last-updated"

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#305]
Assume we need to show a `last-changed` (or `last-updated`) inside a secondary_info with some formatter like `datetime`.

Consider this card:
```
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sun.sun
        show_state: false
        secondary_info:
          attribute: last-changed
          format: datetime

      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sun.sun
        show_state: false
        secondary_info:
          attribute: last-updated
          format: datetime

      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sun.sun
        show_state: false
        secondary_info:
          attribute: last_changed
          format: datetime

      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sun.sun
        show_state: false
        secondary_info:
          attribute: last_updated
          format: datetime
```
![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/3e1c637d-cb58-4428-9bee-6f2305cd5db3)

What we can see here:
1. If attribute is specified like `last-changed` - then `format` is ignored.
2. If attribute is specified like `last_changed` - then `format` is applied.

[According to Docs, the `last-changed` name must be used](https://github.com/benct/lovelace-multiple-entity-row#special-attributes).

**Comment by ildar170975** [comment]
Same for formatting these attributes inside "entities":
```
      - type: custom:multiple-entity-row
        entity: sun.sun
        secondary_info: format default
        entities:
          - attribute: last-changed
            name: last-changed
          - attribute: last-updated
            name: last-updated
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        secondary_info: format datetime
        entities:
          - attribute: last-changed
            name: last-changed
            format: datetime
          - attribute: last-updated
            name: last-updated
            format: datetime
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        secondary_info: format total
        entities:
          - attribute: last-changed
            name: last-changed
            format: total
          - attribute: last-updated
            name: last-updated
            format: total
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        secondary_info: format datetime
        entities:
          - attribute: last_changed
            name: last_changed
            format: datetime
          - attribute: last_updated
            name: last_updated
            format: datetime
        show_state: false
      - type: custom:multiple-entity-row
        entity: sun.sun
        secondary_info: format total
        entities:
          - attribute: last_changed
            name: last_changed
            format: total
          - attribute: last_updated
            name: last_updated
            format: total
        show_state: false
```
![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/f2d309a8-7994-44cb-97b6-f1512d7503e0)
