### ISSUE TITLE
[FR] Add a "default" option for secondary_info

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#306]
Currently (4.5.0) the `default` option is supported for entities only.
Proposal: add a support for the `default` option for secondary_info too.

Example:
```
      - type: custom:multiple-entity-row
        entity: sun.sun
        entities:
          - entity: sensor.some_sensor_1
        show_state: false
        secondary_info:
          entity: sensor.some_sensor_2
          name: false
          hide_unavailable: true
          default: no data
```
