### ISSUE TITLE
The double_tap_action for main entity not working when clicking on the entity's state

### ISSUE THREAD

**Issue by parautenbach** [benct/lovelace-multiple-entity-row#309]
Double clicking works fine for the **main entity** when it's on the name/label, but not on the column with the (main entity's) state value. 

Minimal example.
```
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: switch.test_switch
    state_header: Grid
    tap_action:
      action: more-info
    double_tap_action:
      action: toggle
      confirmation: true
    entities:
      - entity: input_number.test_number
        name: Target
```

See these messages and replies for more info:
https://github.com/benct/lovelace-multiple-entity-row/issues/188#issuecomment-1605752723
https://github.com/benct/lovelace-multiple-entity-row/issues/188#issuecomment-1606112572
https://github.com/benct/lovelace-multiple-entity-row/issues/188#issuecomment-1606117646
