### ISSUE TITLE
tap_action per entity

### ISSUE THREAD

**Issue by SeLLeRoNe** [benct/lovelace-multiple-entity-row#31]
Hi there,
first of all, thanks for this card, it is very useful for my current project :)

I would like to ask if it would be possible to have the "tap_action" to work for each defined entity so that I can decide nothing have to happen, or more spefiically for my case, to open a browser_mod.popup using call-service

Here what I am trying now:
```
                entities:
                  - type: custom:multiple-entity-row
                    entity: input_number.climate_t1_house_workday
                    icon: mdi:timer
                    primary:
                      entity: input_datetime.climate_t1_house_workday_start
                    secondary:
                      entity: input_datetime.climate_t1_house_workday_end
                    tap_action:
                      action: call-service
                      service: browser_mod.popup
                      service_data:
                        title: T1 Workday
                        card:
                          type: entities
                          entities:
                            - input_datetime.climate_t1_house_workday_start
                            - input_datetime.climate_t1_house_workday_end
                            - input_number.climate_t1_house_workday
```

Unfortuntately for now it seems that it is completely ignored, even if I set on each other entity to do nothing:
```
                    primary:
                      entity: input_datetime.climate_t1_house_workday_start
                      tap_action:
                        action: none
```

Would that be possible to integrate?

Thanks
Andrea

**Comment by SeLLeRoNe** [comment]
Ok, I found that there is a service call that can be performed directly inside the card but that doesn't work for the "whole card"

Example:
```
    type: custom:multiple-entity-row
    name: '[[name]]'
    entity: input_number.climate_[[area]]_[[day]]_[[timing]]
    icon: mdi:timer
    primary:
      entity: input_boolean.climate_[[area]]_[[day]]_[[timing]]
      service: browser_mod.popup
      service_data:
        title: Configuration
        card:
          type: entities
          entities:
            - input_boolean.climate_[[area]]_[[day]]_[[timing]]
            - input_datetime.climate_[[area]]_[[day]]_[[timing]]_start
            - input_datetime.climate_[[area]]_[[day]]_[[timing]]_end
            - type: section
              label: Temperature
            - type: custom:slider-entity-row
              entity: input_number.climate_[[area]]_[[day]]_[[timing]]
              full_row: true
    secondary:
      entity: input_datetime.climate_[[area]]_[[day]]_[[timing]]_start
      service: browser_mod.popup
      service_data:
        title: Configuration
        card:
          type: entities
          entities:
            - input_boolean.climate_[[area]]_[[day]]_[[timing]]
            - input_datetime.climate_[[area]]_[[day]]_[[timing]]_start
            - input_datetime.climate_[[area]]_[[day]]_[[timing]]_end
            - type: section
              label: Temperature
            - type: custom:slider-entity-row
              entity: input_number.climate_[[area]]_[[day]]_[[timing]]
              full_row: true
    tertiary:
      entity: input_datetime.climate_[[area]]_[[day]]_[[timing]]_end
      service: browser_mod.popup
      service_data:
        title: Configuration
        card:
          type: entities
          entities:
            - input_boolean.climate_[[area]]_[[day]]_[[timing]]
            - input_datetime.climate_[[area]]_[[day]]_[[timing]]_start
            - input_datetime.climate_[[area]]_[[day]]_[[timing]]_end
            - type: section
              label: Temperature
            - type: custom:slider-entity-row
              entity: input_number.climate_[[area]]_[[day]]_[[timing]]
              full_row: true
    service: browser_mod.popup
    service_data:
      title: Configuration
      card:
        type: entities
        entities:
          - input_boolean.climate_[[area]]_[[day]]_[[timing]]
          - input_datetime.climate_[[area]]_[[day]]_[[timing]]_start
          - input_datetime.climate_[[area]]_[[day]]_[[timing]]_end
          - type: section
            label: Temperature
          - type: custom:slider-entity-row
            entity: input_number.climate_[[area]]_[[day]]_[[timing]]
            full_row: true
```
