### ISSUE TITLE
Lovelace Editor hangs aufter Update to HA 2023.7.0

### ISSUE THREAD

**Issue by jsuelwald** [benct/lovelace-multiple-entity-row#311]
Unsing version 4.5.0

Editing a dhasboard that contains several Items with this addon hangs, raw edit is still possible. Other dhasboard are editable, but the one containing entities with thts addonn makes the UI not possible to operate.

**Comment by ildar170975** [comment]
2023.7
4.5.0
See no issues.
```
type: entities
entities:
  - entity: sun.sun
  - entity: switch.test_switch
  - entity: sensor.processor_use
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - sun.sun
      - sun.sun
  - type: custom:multiple-entity-row
    entity: switch.test_switch
    entities:
      - sun.sun
      - sun.sun
  - type: custom:multiple-entity-row
    entity: sensor.processor_use
    entities:
      - sun.sun
      - sun.sun
```
Tested in Chrome, FF (Win10).
