### ISSUE TITLE
Add support for showing entity output for secondary_info

### ISSUE THREAD

**Issue by andreas-bulling** [benct/lovelace-multiple-entity-row#316]
Various pre-defined information can be shown in `secondary_info` but what does not seem to be possible is to show values/states of an entity or template sensor - in my case the charging state of a battery. When I put `sensor.battery_status` for `secondary_info` it shows that exact string instead of the status itself.

**Comment by ildar170975** [comment]
> When I put sensor.battery_status for secondary_info it shows that exact string instead of the status itself.

Post a SHORT code with your attempt to show a state in the sevobdary_info.

**Comment by andreas-bulling** [comment]
This is the template sensor:
```
{% if states('sensor.victron_vebus_battery_current_227') | float < 0 %}
  Discharging
{% elif states('sensor.victron_vebus_battery_current_227') | float > 0 %}
  Charging
{% else %}
  Standby
{% endif %}
```

And this is the bit in the frontend
```
type: vertical-stack
cards:
  - type: custom:multiple-entity-row
    name: Battery
    entity: sensor.victron_battery_soc
    show_state: false
    state_color: true
    secondary_info: sensor.battery_status
    entities:
      - entity: sensor.victron_vebus_battery_current_227
        name: Current
        format: precision1
        styles:
          font-size: 20px
      - entity: sensor.victron_battery_voltage
        name: Voltage
        format: precision2
        styles:
          font-size: 20px
      - entity: sensor.victron_battery_soc
        name: SOC
        format: precision1
        styles:
          font-size: 20px
```
