### ISSUE TITLE
Cover entity - How to show standard up, stop, down buttons

### ISSUE THREAD

**Issue by Arman-GeDon** [benct/lovelace-multiple-entity-row#319]
Using multiple-entity-row it is not possible to show standard (for entities card) up, stop, down buttons for cover entity.
Toggle: true does not work

**Comment by ildar170975** [comment]
The m-e-r is not supposed to show the same cover entity row as the standard Entities card. The m-e-r does show a state as expected - or an entity’s attribute if needed.  
If you want to show additional controls for a cover entity - propose a Feature request with a detailed description of a desired functionality. “Detailed” means “including the current functionality of displaying states/attributes/icons in “columns”.

**Comment by dvdavide** [comment]
I use something like this:

```
entity: cover.bedroomd
type: custom:multiple-entity-row
name: Bedroom Door
show_state: false
secondary_info:
  attribute: current_position
  postfix: '%'
  prefix: 'Position '
entities:
  - icon: mdi:arrow-up
    tap_action:
      action: call-service
      service: cover.open_cover
      service_data:
        entity_id: cover.bedroomd
  - icon: mdi:stop
    tap_action:
      action: call-service
      service: cover.stop_cover
      service_data:
        entity_id: cover.bedroomd
  - icon: mdi:arrow-down
    tap_action:
      action: call-service
      service: cover.close_cover
      service_data:
        entity_id: cover.bedroomd
```
