### ISSUE TITLE
entity:  sensor.lovelace_multiple_entity_row - Entity not available

### ISSUE THREAD

**Issue by DrCos** [benct/lovelace-multiple-entity-row#321]
used in the example code
```
 - entity:  sensor.lovelace_multiple_entity_row
    type: custom:multiple-entity-row
    name: Attributes (show_state=false)
    show_state: false
    entities:
      - attribute: stargazers
        name: Stars
      - attribute: open_issues
        name: Issues
      - attribute: open_pull_requests
        name: PRs

```
HA 2023.12.1
Have searched, but no insights.   Cannot re-create this entity with the current version of HA.

**Comment by ildar170975** [comment]
1. You have not mentioned what issue you have.
2. The posted code is UNFORMATTED. Place it into triple "`". Use other issues as examples.

**Comment by DrCos** [comment]
I am trying to create a multiple-entity-row with a separate name over each value (as the 'Attributes' line in the example shows).
Using 
`entity: sensor.lovelace_multiple_entity_row`
as type fails, as the editor indicates "Entity not available"

**Comment by ildar170975** [comment]
> as type fails, as the editor indicates "Entity not available"

Same:
![изображение](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/25f3059f-496e-40fd-8617-2031d4295d31)
because this entity is not present in my setup.

You are supposed to use existing entities only:
![изображение](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/bea93bc3-c5dd-4db7-b41b-e6eea7ae3922)
```
type: entities
entities:
  - entity: sun.sun
    type: custom:multiple-entity-row
    name: Attributes (show_state=false)
    show_state: false
    entities:
      - attribute: elevation
        name: Stars
      - attribute: azimuth
        name: Issues
      - attribute: rising
        name: PRs
```
