### ISSUE TITLE
Toogle & Text

### ISSUE THREAD

**Issue by duczz** [benct/lovelace-multiple-entity-row#322]
Hello,

is there a way to set the toogle right and the Button in center to the Button? (See Button and Text Gast, its center to the toggle) - the toggle must be right, because all toggles are in default right

maybe with state_header: "Party       " or a extra text-align?

![image](https://github.com/benct/lovelace-multiple-entity-row/assets/25475385/dcf50db4-0665-4ed3-8e82-50f2d39decbe)

```
entity: input_boolean.advanced_heating_control_wohnzimmer_party_mode
name: Modus
show_state: true
toggle: true
state_header: Party
icon: mdi:arrow-decision
styles:
  width: 60px
  text-align: right
type: custom:multiple-entity-row
entities:
  - entity: input_boolean.advanced_heating_control_wohnzimmer_guest_mode
    name: Gast
    toggle: true
```

**Comment by ildar170975** [comment]
What you posted is not a code. Use formatting.

**Comment by duczz** [comment]
`entity: input_boolean.advanced_heating_control_wohnzimmer_party_mode
name: Modus
show_state: true
toggle: true
state_header: Party
icon: mdi:arrow-decision
styles:
  width: 60px
  text-align: right
type: custom:multiple-entity-row
entities:
  - entity: input_boolean.advanced_heating_control_wohnzimmer_guest_mode
    name: Gast
    toggle: true
`

**Comment by duczz** [comment]
the code button diesnt work here, always unformat, see picture.
![image](https://github.com/benct/lovelace-multiple-entity-row/assets/25475385/9953d59c-aa7f-4573-8b90-4aa09505ca2d)

**Comment by ildar170975** [comment]
paste code into triple "`"

**Comment by duczz** [comment]
you see on top, that these is nor working, these already exist

**Comment by ildar170975** [comment]
We are spending to much time for this (.
```
formatted code
```

**Comment by duczz** [comment]
its ``` not `...

**Comment by ildar170975** [comment]
> triple "`"

?

**Comment by duczz** [comment]
maybe i was blind haha

**Comment by ildar170975** [comment]
Seems that this was already discussed & answered:
https://community.home-assistant.io/t/lovelace-multiple-entity-row/109109/397?u=ildar_gabdullin

**Comment by duczz** [comment]
This code works.

```
entity: sun.sun
name: Modus
icon: mdi:temperature-celsius
show_state: false
type: custom:multiple-entity-row
entities:
  - entity: input_boolean.advanced_heating_control_schlafzimmer_guest_mode
    name: Gast
    toggle: true
    styles:
      width: 100px    
  - entity: input_boolean.advanced_heating_control_schlafzimmer_party_mode
    name: Party
    toggle: true

```
