### ISSUE TITLE
Handle or silence RangeError?

### ISSUE THREAD

**Issue by Floppe** [benct/lovelace-multiple-entity-row#324]
When an entity has UOM = c/kWh, then perhaps do not try to treat it as a currency so the debug console is not filled with errors?

`RangeError: Invalid currency code : c/kWh
    at new NumberFormat (<anonymous>)
    at Mt (multiple-entity-row.js?hacstag=178921037450:1:19956)
    at multiple-entity-row.js?hacstag=178921037450:1:33612
    at multiple-entity-row.js?hacstag=178921037450:1:34897
    at c.value (multiple-entity-row.js?hacstag=178921037450:1:34932)
    at c.value (multiple-entity-row.js?hacstag=178921037450:1:31297)
    at multiple-entity-row.js?hacstag=178921037450:1:29878
    at Array.map (<anonymous>)
    at c.value (multiple-entity-row.js?hacstag=178921037450:1:29852)
    at c.update (multiple-entity-row.js?hacstag=178921037450:1:14837)`

**Comment by ildar170975** [comment]
Consider posting your MINIMAL code causing the issue.
Cannot reproduce it:

![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/ab03116d-2a8c-452a-9646-b3c52205d8e9)

```
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: zone.home
    unit: c/kWh
    entities:
      - entity: zone.home
        unit: c/kWh
  - type: custom:multiple-entity-row
    entity: sensor.test_unit
    entities:
      - entity: sensor.test_unit
```
![image](https://github.com/benct/lovelace-multiple-entity-row/assets/71872483/fa14e22c-91b9-4b8b-922c-281d3e352592)
