### ISSUE TITLE
Add support for icon_color

### ISSUE THREAD

**Issue by andreas-bulling** [benct/lovelace-multiple-entity-row#325]
It currently doesn't seem to be possible to customize the icon color(s) similar to other entity cards, e.g. depending on the state of a sensor:

`icon_color: >- {{ is_state('binary_sensor.garage_1_reed', 'off') | iif('green', 'red') }}`

**Comment by ildar170975** [comment]
>  similar to other entity cards,

Like which cards particularly?


> customize the icon color(s) 

card-mod.

**Comment by andreas-bulling** [comment]
For example "mushroom-template-card" directly supports changing icon_color.

Do you happen to have an example for how to do the above with card-mod? I've tried for half an hour but without success :(

**Comment by ildar170975** [comment]
>  "mushroom-template-card" directly supports changing icon_color.

Unfortunately, this is the only example.
As for standard cards - only a Tile card supports `icon_color` (but not a "entity-row" card).

> how to do the above with card-mod

Suggest to ask all card-mod related questions in the [dedicated card-mod Community thread](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744).
You may find examples which could be useful:
1st post of the thread -> link at the bottom -> styles for m-e-r.

**Comment by danielbrunt57** [comment]
I've just finished successfully using card_mod to change the icon for the primary entity in multiple-entity-row without having the secondary entities icon(s) change as well.
Here's my code for changing the icon.
Note: I'm using the decluttering card & templates hence the `[[blind]]` reference:
```
        - type: entities
          entities:
            - entity: cover.[[blind]]
              type: custom:multiple-entity-row
              name: ' '
              show_state: false
              card_mod:
                style:
                  hui-generic-entity-row:
                    $: |
                      state-badge {
                        --card-mod-icon: {{ iif(states('cover.[[blind]]') == "open", "phu:blind-tilt-open", "phu:blind-tilt-closed") }}
                        }
              entities:
                - entity: sensor.[[blind]]_battery_level
                  name: Battery
                - entity: sensor.[[blind]]_battery_level
                  name: false
                  icon: true
          show_header_toggle: false
          state_color: false
          card_mod:
            class: inline-card
```
Before I achieved that, I was trying:
```
              card_mod:
                style:
                  :host {
                        --card-mod-icon: {{ iif(states('cover.[[blind]]') == "open", "phu:blind-tilt-open", "phu:blind-tilt-closed") }}
                  }
```
but that was changing the icon for **_all_** entities in the row.

@andreas-bulling 
You should be able to acheive an icon color change with:
```
              card_mod:
                style:
                  :host {
                        color: {{ iif(states('binary_sensor.garage_1_reed') == "off", "green", "red") }}
                  }
```
My version of the code works for the color of the primary entity icon.
```
              card_mod:
                style:
                  hui-generic-entity-row:
                    $: |
                      state-badge {
                        --card-mod-icon: {{ iif(states('cover.[[blind]]') == "open", "phu:blind-tilt-open", "phu:blind-tilt-closed") }};
                        color: {{ iif(states('cover.[[blind]]') == "open", "green", "red") }}
                      }
```
![image](https://github.com/benct/lovelace-multiple-entity-row/assets/49846893/d56c53b7-68ef-49be-aeb0-234489c8a083)

![image](https://github.com/benct/lovelace-multiple-entity-row/assets/49846893/4f61794e-2ffa-46bc-81e2-8f241877066f)
