### ISSUE TITLE
Add spacing enhancement (and option[s])?

### ISSUE THREAD

**Issue by mrand** [benct/lovelace-multiple-entity-row#33]
Enhancement request (but even without any of these, thank you making this awesome addition to Lovelace!)

I'm looking for a way to get my primary entity more towards the middle rather than right justified to spread out the white space and make it not look so busy.  Someone might want to do the same with a primary/secondary or (rarely?) even a primary/secondary/tertiary setup.

One obvious solution is a row-level justification option. 

The second solution would be a blank entity. It could solve my use case, and would also cover a case where someone wants to display two extra entities, either with extra space to the right of the two entities, or extra space between them (i.e primary and tertiary contain real entities, and secondary would be blank).

Adding both would obviously open up the additional spacing possibilities.

![image](https://user-images.githubusercontent.com/435987/73558959-cba9de80-4419-11ea-9f8d-153c63627c33.png)

```
          - entity: lock.front_door_lock_9
            secondary_info: last-changed
            type: custom:multiple-entity-row
            justify: center               # option 1.  Someone might want left also
            primary:
              attribute: changed_by_name
              name: Last opened by
            secondary:
              name: "                   "  # option 2: dummy using spaces for width 
```

When I thought about the above, I realized spacing in the blank name could solve a different issue.  Take my Leak sensors below as an example.  It would look better if Fridge (and the entity value below it) was moved to the left slightly.  I tried adding spaces to the name, but they appear to be ignored:

![image](https://user-images.githubusercontent.com/435987/73561958-b041d200-441f-11ea-9650-dba36cfead74.png)

```
          - entity: sensor.dishwasher_sensor_battery
            name: Leak sensors
            type: custom:multiple-entity-row
            name_state: Dishwasher
            primary:
              entity: sensor.fridge_sensor_battery
              name: "  Fridge  "              # honoring spaces could make spacing look nicer
            secondary:
              entity: sensor.waterheater_sensor_battery
              name: Hallway
```
