### ISSUE TITLE
hide_unavailable: true does not hide

### ISSUE THREAD

**Issue by Mariusthvdb** [benct/lovelace-multiple-entity-row#332]
consider:
```
  - type: custom:multiple-entity-row
    entity: sensor.kelder_aanbouw_hygro_temp_temperature
    hide_unavailable: true
    state_header: Temp
    name: Kelder
    entities:
      - entity: sensor.kelder_aanbouw_hygro_temp_humidity
        name: Vocht
      - entity: sensor.kelder_aanbouw_hygro_temp_battery
        name: Battery
    secondary_info:
      entity: sensor.kelder_aanbouw_hygro_temp_signal_strength
      name: Signal
```

while the `sensor.kelder_aanbouw_hygro_temp_temperature` entity is unavailable:

<img width="995" alt="Scherm­afbeelding 2024-02-13 om 13 06 11" src="https://github.com/benct/lovelace-multiple-entity-row/assets/33354141/08752c84-5ca4-4915-a928-9307b2469b34">

still showing:

<img width="542" alt="Scherm­afbeelding 2024-02-13 om 13 04 03" src="https://github.com/benct/lovelace-multiple-entity-row/assets/33354141/a92029b3-6a36-43b1-8a29-0d61a44dfdf2">

supposed to be hidden from the view.

HA 2024.2
M-E-R: 4.5.0

using core conditional does work as hoped for:
```
card:
  type: conditional
  conditions:
    - entity: sensor.[[id]]_hygro_temp_temperature
      state_not: unavailable
  card:
    type: custom:multiple-entity-row
    entity: sensor.[[id]]_hygro_temp_temperature
    # hide_unavailable: true
    state_header: Temp
    name: '[[name]]'
    <<: &width
      styles:
        width: 60px
        text-align: center
    entities:
      - entity: sensor.[[id]]_hygro_temp_humidity
        name: Vocht
        <<: *width
      - entity: sensor.[[id]]_hygro_temp_battery
        name: Battery
        <<: *width
    secondary_info:
      entity: sensor.[[id]]_hygro_temp_signal_strength
      name: Signal
```

**Comment by cpw7922** [comment]
I've got the same issue. Did you figure it out?

**Comment by Mariusthvdb** [comment]
nope, the Entity option is bugged, and no response from the author yet, so we are left to use the core conditional.


<img width="591" alt="Scherm­afbeelding 2024-05-22 om 13 58 35" src="https://github.com/benct/lovelace-multiple-entity-row/assets/33354141/1c0531e1-a6c1-40a9-93a7-47b94df6266b">


we can do this (add the `hide_unavailable` option to the entities, and that works):
```
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: sensor.kelder_aanbouw_hygro_temp_temperature
    hide_unavailable: true
    state_header: Temp
    name: Kelder
    entities:
      - entity: sensor.kelder_aanbouw_hygro_temp_humidity
        name: Vocht
        hide_unavailable: true
      - entity: sensor.kelder_aanbouw_hygro_temp_battery
        name: Battery
        hide_unavailable: true
    secondary_info:
      entity: sensor.kelder_aanbouw_hygro_temp_signal_strength
      hide_unavailable: true
      name: Signal
```

<img width="591" alt="Scherm­afbeelding 2024-05-22 om 14 03 34" src="https://github.com/benct/lovelace-multiple-entity-row/assets/33354141/92a8dfde-4b4e-4ada-8373-ea025f281326">

It still shows the main entity though, and that ofc is the issue at hand
