### ISSUE TITLE
The sensor is displayed with a decimal part that should not be there

### ISSUE THREAD

**Issue by man55** [benct/lovelace-multiple-entity-row#333]
I have sensors that are specified to display as an integer.
In the standard HOME card they are displayed correctly as an integer.
But when I use the lovelace-multiple-entity-row, these sensors are displayed with a decimal place, which is very annoying.
I tried changing regional settings, but it has no effect.

```
type: entities
entities:
 .....
      - entity: sensor.xxxxxxxx_fanrpm_combine
        name: fanrpm
        styles:
          width: 74px
          text-align: center
```

<img width="402" alt="Screenshot 2024-02-22 183250" src="https://github.com/benct/lovelace-multiple-entity-row/assets/30772900/ff04de17-13df-4f01-85bd-332220e357c3">
<img width="85" alt="Screenshot 2024-02-22 183224" src="https://github.com/benct/lovelace-multiple-entity-row/assets/30772900/60be0841-6e9c-4ae4-be09-9a05691ac0ba">
<img width="86" alt="Screenshot 2024-02-22 183217" src="https://github.com/benct/lovelace-multiple-entity-row/assets/30772900/1823a4c5-f6c8-4f27-b4ea-8f27cb07e090">
