### ISSUE TITLE
Tap actions do not work for sub items if they do not have an entity

### ISSUE THREAD

**Issue by i00** [benct/lovelace-multiple-entity-row#337]
I want to have a sub item without an entity so that I can show some custom text so I have:
``` yaml
- entity: none
  default: 'Boost'
  tap_action:
    action: navigate
    navigation_path: /lovelace/ev-boost
```

It looks like you can click on it - but if the entity is set up this way, clicking on it does nothing!
