### ISSUE TITLE
hold_action and double_tap_action not working

### ISSUE THREAD

**Issue by morenod** [benct/lovelace-multiple-entity-row#338]
With following configuration, hold and double tap are not working:

```
type: entities
entities:
  - entity: switch.xxx1
    name: XXX
    icon: mdi:power
  - entity: light.xxx2
    icon: mdi:ceiling-fan-light
    name: xxx2
    type: custom:multiple-entity-row
    state_color: true
    show_state: false
    toggle: true
    entities:
      - entity: switch.switch_relay_1
        icon: mdi:power
        name: false
        state_color: true
        tap_action:
          action: toggle
      - entity: fan.fan_2
        name: false
        toggle: true
        icon: mdi:fan
        state_color: true
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        double_tap_action:
          action: more-info
title: YYY
show_header_toggle: false
state_color: true
```

![image](https://github.com/benct/lovelace-multiple-entity-row/assets/25103450/2b87f782-8771-4574-b2ab-17172e2063b8)
