### ISSUE TITLE
Wrong visualization of attributes ("," instead of ".") - no localization override

### ISSUE THREAD

**Issue by bcutter** [benct/lovelace-multiple-entity-row#339]
I have an entity `update.lock_firmware_update` with attributes

```
auto_update: false
installed_version: 8.34
in_progress: false
latest_version: 8.35
...
```

When using the card like this

```
      - type: custom:multiple-entity-row
        entity: update.lock_firmware_update
        name: Nuki Hub-Version
        icon: mdi:counter
        toggle: false
        state_color: false
        show_state: true
        secondary_info: last-changed
        entities:
          - entity: update.lock_firmware_update
            attribute: installed_version
            name: Ist
          - entity: update.lock_firmware_update
            attribute: latest_version
            name: Neu
        state_header: Update?
        column: false
```

I get this:
![grafik](https://github.com/user-attachments/assets/4dce86c0-c522-4691-a5eb-483d5ad28874)

**Problem:** the original attributes version is with a dot (.) instead of a commata (,) - the card is showing them wrong.

I guess localization (UI language is German) kicks in here and `custom:multiple-entity-row` still seems to be unable to override this behaviour. No other card shows attributes with wrong characters broken this way.
