### ISSUE TITLE
Is it possible to hide somehow icon and name? 

### ISSUE THREAD

**Issue by denveronly** [benct/lovelace-multiple-entity-row#341]
Hey all, i tried everything but i just cant hide the icon and name.
i tried card-mod but it doesnt work.

![image](https://github.com/user-attachments/assets/2e7a644c-a38e-4ed9-b68b-c92472816cc4)

my code looks like this
`
- entity: script.update_solar_forecast
                type: custom:multiple-entity-row
                name: Solcast
                state_header: Update
                show_icon: false
                toggle: true
                state_color: false
                icon: mdi:solar-power         
                entities:
                  - entity: sensor.solcast_pv_forecast_forecast_today
                    name: Today
                    format: precision0
                    tap_action:
                      action: more-info
                  - entity: sensor.solcast_pv_forecast_forecast_tomorrow
                    name: Tomm
                    format: precision0
                    tap_action:
                      action: more-info
                  - entity: sensor.solcast_pv_forecast_forecast_day_3
                    name: Day3
                    format: precision0
                    tap_action:
                      action: more-info
                  - entity: sensor.solcast_pv_forecast_forecast_day_4
                    name: Day4
                    format: precision0
                    tap_action:
                      action: more-info
                  - entity: sensor.solcast_pv_forecast_forecast_day_5
                    name: Day5
                    format: precision0
                    tap_action:
                      action: more-info
                  - entity: sensor.solcast_pv_forecast_forecast_day_6
                    name: Day6
                    format: precision0
                    tap_action:
                      action: more-info
                card_mod:
                  style: |
                    hui-generic-entity-row {
                      display: none;
                    }
`

**Comment by kwkid** [comment]
forget about card_mod...this is way i use

**where you have**
entity: script.update_solar_forecast
type: custom:multiple-entity-row
name: Solcast
state_header: Update
show_icon: false
toggle: true
state_color: false
icon: mdi:solar-power

**try**
entity: script.update_solar_forecast
type: custom:multiple-entity-row
**name: ' '**
state_header: Update
show_icon: false
toggle: true
state_color: false
**icon: mdi:none**

**Comment by ildar170975** [comment]
> forget about card_mod

I would not be so confident since in SOME use-cases this advice may not give a desired effect since `entities-row` element will occupy SOME part of a row, not a whole row.

2 OP: ask in the main card-mod thread of Community (in case you have not asked already but have not closed this issue yet).

**Comment by Airblader** [comment]
FWIW, choosing a non-existing icon seems to work for me. For the name you can use `name: ''`.

**Comment by nicknol** [comment]
according to the documentation you could suppress the name by setting it to false.
`name: false`

**Comment by ildar170975** [comment]
> according to the documentation you could suppress the name by setting it to false.
> `name: false`

This is not about the main entity.

**Comment by nicknol** [comment]
perhaps I didn't get the point. 
For me `name: false` works for all entities: for the main entity but as well for the secondary entities. 
It needs to be set per entity.

**Comment by ildar170975** [comment]
> For me `name: false` works for all entities: for the main entity but as well for the secondary entities.

I was wrong.
Yes, `name: false` works for the main entity as well:
![изображение](https://github.com/user-attachments/assets/61d4c86d-3a0e-4221-8072-4f592b60a256)

There is a confusion in Docs: for additional entities it is said clearly about `false`, for the main entity - it is not:
![изображение](https://github.com/user-attachments/assets/39da8edf-0442-4739-8da0-29adba309a10)

But anyway, hiding an icon by setting an empty/non-existing icon + hiding a name MAY help in some case - and MAY NOT in case of many additional entities ([as it was already noted](https://github.com/benct/lovelace-multiple-entity-row/issues/341#issuecomment-2327306757)):
```
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - &ref_icon
        entity: sun.sun
        icon: true
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
  - type: custom:multiple-entity-row
    entity: sun.sun
    entities:
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
  - type: custom:multiple-entity-row
    entity: sun.sun
    name: false 
    icon: mdi:none
    entities:
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
      - *ref_icon
```
![изображение](https://github.com/user-attachments/assets/c2ba2909-4322-4989-a891-3d027e6cf539)
