### ISSUE TITLE
[FR] Support of chaged actions (2024.8)

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#342]
2024.8 added changes in actions.
[Docs.](https://www.home-assistant.io/dashboards/actions/#tap-action)
Please reflect these changes in `multiple-entity-row`.

**Comment by drew1kun** [comment]
+1 this..

Tried with the scene and it does not work unfortunately.

```yaml
  tap_action:
    action: perform-action
    perform_action: scene.turn_on
    target:
       entity_id: scene.bedroom_mourn_light
```
