### ISSUE TITLE
Press tap_action ?

### ISSUE THREAD

**Issue by brenard** [benct/lovelace-multiple-entity-row#345]
I can't find a way to configure a press action on tap on button included entity. Their is a way for that or may be we coud add a `tap_action: press` ?

**Comment by ildar170975** [comment]
Could you post a SUPER SHORT code demonstrating the issue?
[Perhaps here you will find an answer.](https://github.com/benct/lovelace-multiple-entity-row/issues/315)

**Comment by brenard** [comment]
You're right, this is the solution:

```yaml
entity: sensor.dimmer_b128_last_backup
type: custom:multiple-entity-row
name: Cuve de sortie
show_state: false
entities:
  - entity: button.dimmer_b128_backup_configuration
    toggle: true
    name: Sauvegarde
    icon: mdi:download
    tap_action:
      action: call-service
      service: button.press
      service_data:
        entity_id: button.dimmer_b128_backup_configuration
```
When I looked for a solution, I tried it, but I seem I have to pass the entity ID not in the service data but in a `target` key at the same level than `service_data`. Firstly I try to put the entity ID in the `action` key, as the autocompletion propose it and let's supposed it's could works (it's doesn't). May be an example in the doc could avoid some mistake of this type.

Thank for your help!
