### ISSUE TITLE
Button trigger automation and show timer?

### ISSUE THREAD

**Issue by antgustech** [benct/lovelace-multiple-entity-row#350]
I currently have this card:

```
type: entities
entities:
  - entity: light.ikea_e14_1
    type: custom:multiple-entity-row
    name: Byrå
    toggle: true
  - entity: automation.toggle_window_lights_when_pressed
    icon: mdi:timer-sand
    type: button
    name: Starta timer
    tap_action:
      action: call-service
      service: automation.trigger
      target:
        entity_id: automation.toggle_window_lights_when_pressed
      data:
        skip_condition: true
  - entity: timer.bedroom_light_timer
    name: Timer tid
title: Huvudsovrum
show_header_toggle: false
state_color: false



```
![light](https://github.com/user-attachments/assets/2a01a5e7-2166-43bf-81ca-41e7fb57eec0)

The idea is to be able to turn a light on and off with the toggle as well as starting it via a timer. 

Now, I'm trying to rewrite this with multiple-entity-row to put it all on the same row. However, the timer button does not work,
"Failed to perform the action automation/trigger. must contain at least one of entity_id, device_id, area_id, floor_id, label_id." and the timer does not show the time either, only "Active" or "Idle".
![multiple](https://github.com/user-attachments/assets/a8dd4be2-0533-4616-ac3a-018841dd706c)

```
type: entities
entities:
  - entity: light.ikea_e14_1
    type: custom:multiple-entity-row
    name: Byrå
    toggle: true
    entities:
      - entity: automation.toggle_window_lights_when_pressed
        icon: mdi:timer-sand
        type: button
        name: Starta timer
        tap_action:
          action: call-service
          service: automation.trigger
          target:
            entity_id: automation.toggle_window_lights_when_pressed
          data:
            skip_condition: true
      - entity: timer.bedroom_light_timer
        name: Timer tid
title: Huvudsovrum
show_header_toggle: false
state_color: false
```

How do I fix this so that it looks equivalent to my orignal card but on one row instead?   Bonus points if its possible to use a more..clear button instead of "RUN"
