### ISSUE TITLE
Value for secondary_info from other entity shows as "undefined" post HA Core update to 2025.1.1

### ISSUE THREAD

**Issue by stomko11** [benct/lovelace-multiple-entity-row#352]
I used to use card to display multiple values, among others battery % which was taken from different entity than the main one.
I noticed that post recent HA core update, these values show "undefined". I tried to change config, but I don't seem to be able to refer value from another entity anymore?
Anyone has any clue what could be wrong here?

Example card:
```
type: custom:layout-card
layout_type: masonry
layout: {}
cards:
  - type: entities
    entities:
      - entity: sensor.bathroom_e6_sensor_temperature
        type: custom:multiple-entity-row
        name: Bathroom
        icon: mdi:shower-head
        styles:
          width: 50px
          text-align: center
        state_header: Currently
        secondary_info:
          entity_id: sensor.bathroom_e6_sensor_battery
          attribute: battery
          unit: "% Battery"
        entities:
          - entity: climate.bathroom
            attribute: hvac_action
            name: Heating
            styles:
              width: 30px
              text-align: center
          - entity: sensor.bathroom_e6_sensor_humidity
            name: Humidity
            styles:
              width: 50px
              text-align: center
          - entity: climate.bathroom
            attribute: temperature
            name: Set
            styles:
              width: 30px
              text-align: center
```

This is how it looks like:
![image](https://github.com/user-attachments/assets/07ad7570-6f5a-4330-a572-232bfa7d04b3)

And this is the entity that holds battery %:
![image](https://github.com/user-attachments/assets/5027b243-471e-495a-ae94-89ddf455ff4d)

I also tried to modify secondary info section and removed the "battery" attribute, and then I need to change entity_id to entity as I get error that either entity, attribute or icon needs to be specified, but still, value isn't returned, but it looks like this:
```
        secondary_info:
          entity: sensor.bathroom_e6_sensor_battery
          unit: "% Battery"
```
![image](https://github.com/user-attachments/assets/177d5974-f05d-4ce7-9c6d-39ac94f66535)

**Comment by ildar170975** [comment]
> noticed that post recent HA core update, these values show "undefined".

I doubt that it worked before the update since you are trying to use a “battery” attribute of an entity which does not have it.

> tried to modify secondary info section and removed the "battery" attribute, and then I need to change entity_id to entity

There is no such option “entity_id”, it is clearly said up in Docs that you must use “entity”. 

Suggest to ask questions in Community first before reporting a “bug”.

**Comment by jpettitt** [comment]
Confirmed it works if you use `entity`

```
type: entities
entities:
  - entity: sensor.outside_temperature
    format: precision1
    type: custom:multiple-entity-row
    secondary_info:
      entity: climate.hvac
      attribute: temperature
    entities:
      - entity: climate.hvac
        attribute: hvac_action
        name: Heating
        styles:
          width: 30px
          text-align: center
      - entity: sensor.outside_humidity
        name: Humidity
      - entity: climate.hvac
        attribute: temperature
        name: Set
```

<img width="468" height="92" alt="Image" src="https://github.com/user-attachments/assets/1f5761b5-dcfa-4ad3-9a45-4aec601e1fae" />
