### ISSUE TITLE
Can't style secondary_info when there is entity in it

### ISSUE THREAD

**Issue by mschilder** [benct/lovelace-multiple-entity-row#353]
I can't seem to style the secondary_info. This is what I have and the secondary_info does not become green.

```
type: entities
entities:
  - type: section
  - entity: automation.battery_charge
    type: custom:multiple-entity-row
    name: Import
    icon: mdi:battery-plus-outline
    unit: " "
    toggle: true
    format: precision0
    secondary_info:
      entity: input_number.ess_import_threshold
      styles:
        color: green
...
```
