### ISSUE TITLE
More than one automation with toggle:true creates another toggle

### ISSUE THREAD

**Issue by mschilder** [benct/lovelace-multiple-entity-row#354]
I have this code (playing around with this awesome card):

```
title: Settings
type: entities
entities:

  - entity: automation.battery_charge
    type: custom:multiple-entity-row
    name: Import
    toggle: true
    icon: mdi:battery-plus-outline
    entities:
      - entity: input_number.ess_import_hours

  - entity: automation.battery_discharge
    type: custom:multiple-entity-row
    name: Export
    toggle: true
    icon: mdi:battery-minus-outline
    entities:
      - entity: input_number.ess_export_hours
```

But it results in 3 toggles (instead of 2)

[Screenshot 2025-01-12 at 21 27 58](https://github.com/user-attachments/assets/9c1fd539-f455-4408-8201-6e09a07a0660)
