### ISSUE TITLE
hide_if does not work with string value

### ISSUE THREAD

**Issue by pdwonline** [benct/lovelace-multiple-entity-row#356]
I use a timer. When the timer is Idle, it returns the string 'idle'  In that case, I like to hide it. However it keeps showing..
Here is my YAML config for it:

 ```
 - entity: group.presence_users
    type: custom:multiple-entity-row
    name: Iemand aanwezig
    icon: mdi:human
    tap_action:
      action: none
    show_state: false
    state_color: true
    entities:
      - entity: timer.presence_check
        state_color: true
        name: controleren
        hide_if:
          value: idle
        tap_action:
          action: more-info
 
```
