### ISSUE TITLE
Replace Toggle with Icon for Main Entity

### ISSUE THREAD

**Issue by oneseventhree** [benct/lovelace-multiple-entity-row#359]
Hi,

I currenlty have this:

<img width="436" alt="Image" src="https://github.com/user-attachments/assets/6238c59c-19e8-4be9-aefc-67f4afd4fdf9" />

but I want to change the toggle for 'Pendent' to a lamp icon but it does not change the toggle to the icon.  Is this possible?

Full code
```
entity: light.bedroom_pendant
type: custom:multiple-entity-row
name: Side Lights
state_header: Pendant
icon: mdi:lamp
toggle: true
entities:
  - entity: light.bedroom_lamp
    name: Lamp
    toggle: true
    icon: mdi:lightbulb
card_mod:
  style: |
    :host {
      --card-mod-icon-color:
         {% if is_state('light.bedroom_lamp','on') 
            or is_state('light.bedroom_pendant','on') %}
            #ffc107
         {% else %}
            #44739e
         {% endif %}
        }
```

**Comment by muratcesmecioglu** [comment]
Just use `show_state: false` on main entity and then add a new sub-entity for Pendant

```
type: entities
entities:
  - entity: light.grup_salonled
    type: custom:multiple-entity-row
    state_header: Led
    name: Işıklar
    icon: mdi:lightbulb-group
    show_state: false
    entities:
      - entity: switch.grup_salonkenar
        name: Kenar
        icon: mdi:lightbulb-group
        tap_action:
          action: toggle
      - entity: switch.grup_salonorta
        name: Orta
        icon: mdi:lightbulb-group
        tap_action:
          action: toggle
      - entity: light.grup_salonled
        name: Led
        icon: mdi:lightbulb-group
        tap_action:
          action: toggle
title: Salon
state_color: false
show_header_toggle: false
```


![Image](https://github.com/user-attachments/assets/2ba2bad3-716d-43dd-94d8-c185f4518094)
