### ISSUE TITLE
Toggle triggers multiple lights

### ISSUE THREAD

**Issue by bart1604** [benct/lovelace-multiple-entity-row#38]
Hi,

I have a strange issue, when I toggle "Staande lampen" it also toggles "Spot TV" for some reason. These entities are not in a group together or what so ever. When I do it the other way around (toggle "Spot TV") the "Staande lampen" stays off.

I have multiple of these "grouped" toggels for some reason. this only happens in this lovelace-multiple-entity-row feature. When I toggle "Staande lampen" in a default entity card, there is no issue.

I've downloaded the latest version this morning from this github page.

Is someone having the same issue and/or has a solution for this?

For this specifiek case this is my code:
 ```
entities:
  - label: Woonkamer
    type: section
  - entity: input_boolean.lightonoffstaandelampen
    hide_state: false
    name: Staande lampen
    toggle: true
    type: 'custom:multiple-entity-row'
  - entity: light.spot_tv
    hide_state: false
    name: Spot TV
    toggle: true
    type: 'custom:multiple-entity-row'
  - label: Achtertuin
    type: section
  - entity: light.achtertuin
    hide_state: false
    name: Achtertuin
    toggle: true
    type: 'custom:multiple-entity-row'
  - label: Hal
    type: section
  - entity: input_boolean.lightonoffhal
    name: Hal
    primary:
      entity: input_number.hal_brightness
    toggle: true
    type: 'custom:multiple-entity-row'
  - entity: light.voordeur
    name: Voordeur
    toggle: true
    type: 'custom:multiple-entity-row'
  - label: Overloop
    type: section
  - entity: light.hal_boven
    name: Overloop
    toggle: true
    type: 'custom:multiple-entity-row'
  - label: Zolder
    type: section
  - entity: light.voorzolder
    name: Zolder
    toggle: true
    type: 'custom:multiple-entity-row'
title: Lampen
type: entities

```
