### ISSUE TITLE
URL tap action

### ISSUE THREAD

**Issue by fpd2** [benct/lovelace-multiple-entity-row#49]
Would it be possible to add a tap_action called 'url' (like implemented for the standard 'Entities Card') for linking to web pages, so that one could set the tap action something like:
```yaml
- type: 'custom:multiple-entity-row'
  entity: sensor.sensor1
  entities:
    - icon: 'mdi:link-variant'
      tap_action:
        action: url
        url_path: 'http://x.x.x.x'
```
Many thanks in advance!
