### ISSUE TITLE
Disable divider

### ISSUE THREAD

**Issue by lenisko** [benct/lovelace-multiple-entity-row#5]
Is there any way to disable `divider` between entities ?

**Comment by benct** [comment]
Not sure what divider you mean. The horizontal line between the rows in the example? If so just remove the `- type: section` and adjoining `label` part of the config.

**Comment by lenisko** [comment]
You are correct.
Thanks it helped! didn't realized it was so obvious...
```
entities:
  - type: section
  - entity: sensor.pressure_24
    icon: 'mdi:home-city'
    name: Office Out
    primary:
      entity: sensor.temperature_22
      name: false
    secondary:
      entity: sensor.humidity_23
      name: false
    type: 'custom:multiple-entity-row'
  - entity: sensor.pressure_13
    icon: 'mdi:home-variant'
    name: Salon Out
    primary:
      entity: sensor.temperature_11
      name: false
    secondary:
      entity: sensor.humidity_15
      name: false
    type: 'custom:multiple-entity-row'
show_header_toggle: false
title: Sensors
type: entities
```
