### ISSUE TITLE
Strange request - monitor other entities

### ISSUE THREAD

**Issue by i00** [benct/lovelace-multiple-entity-row#59]
I have an entity that does not refresh in your great multiple-entity-row because I have to refer to it dynamically as a string (as I am building a list of multiple-entity-row's dynamically) based on a property of another entity.. the problem is that, as such this entity is not monitored for changes, so when it updates, the row does not.

Is it possible to have a monitored option like:
``` yaml
type: custom:multiple-entity-row
monitored: 'device_tracker.test,device_tracker.test2'
# or
monitored:
  - 'device_tracker.test'
```
Of course it would still automatically update on detected referenced changes.. these would be additional entities.

Thanks

**Comment by benct** [comment]
I *think* I understand your issue here but I am quite sure this not possible, or if so very difficult, to  support in custom lovelace cards/plugins. I have no direct control over state changes and/or (re-)rendering as far as I know. Sorry :(

**Comment by i00** [comment]
Ok... some background:
I have the following card (note me (Kris) below):
![image](https://user-images.githubusercontent.com/1435262/76576517-05d4c880-650e-11ea-9930-c09920c381ed.png)
The entities are device trackers from my WiFi router ... when a phone is on WiFi it is Home...
When it is not home it is away ... or if it has a geo_sensor attribute defined it uses that entity to list the information about the persons location.

To do this I have setup the entities in the customize.yaml:
```yaml
device_tracker.i00_phone:
  friendly_name: Kris
  home_member: true
  geo_sensor: sensor.oneplus_a3003_geocoded_location
```
Now ... the entity will only update when the state of device_tracker.i00_phone changes NOT when sensor.oneplus_a3003_geocoded_location does....

Hope that makes sense :)
