### ISSUE TITLE
Support for Special Row Elements in an Entity Row

### ISSUE THREAD

**Issue by KenCote** [benct/lovelace-multiple-entity-row#6]
Looking at this link:  https://www.home-assistant.io/lovelace/entities/  -- see the section on "Special Row Elements."  Specifically, having the ability to launch a script from a button in-line on the entity row would be excellent.

I could see the config being something like:

```
 entities:
 - entity: input_datetime.sleep_time_shutoff
   name: Sleep Timer
   type: custom:multiple-entity-row
   secondary_info: last-changed
   hide_state: true
   primary:
     type: call-service
     name: false
     action_name: '+30'
     service: script.sleep_timer_add_30
```

What this would show is a single row (sorry for the ASCII only -- the "[+ 30]" represents a button that launches the script):

`Sleep Timer   -----------------------------    [+ 30]  22:34`

Let me know if you think this makes sense and if I can help in any other way.
