### ISSUE TITLE
name and format at the same time in secondary_info

### ISSUE THREAD

**Issue by McGiverGim** [benct/lovelace-multiple-entity-row#60]
If I add a `name` and a `format` in the `secondary_info` the name is hidden. If I remove the `format` the name appears again.

Sample:
```yaml
type: entities
title: Copias de seguridad
show_header_toggle: false
entities:
  - entity: binary_sensor.snapshots_stale
    name: Problema en copias
    secondary_info:
      entity: sensor.snapshot_backup
      attribute: last_snapshot
      name: Última copia
      format: datetime
    type: 'custom:multiple-entity-row'
```
