### ISSUE TITLE
icon for states

### ISSUE THREAD

**Issue by i00** [benct/lovelace-multiple-entity-row#61]
Hi... If something is boolean ... can you have another icon like:

icon: mdi:...
**icon_off**: mdi:...

That allows the icon to be changed depending on the entities state?
Thanks

**Comment by i00** [comment]
Sorry ... how does #71 fix this? ... I noticed you stated that you now do intend to make the card implement templating soon tho... so I guess I wait for that.

**Comment by benct** [comment]
Uhm... I really have no idea how this got linked to #71... Reopening it.

**Comment by drzony** [comment]
#71 makes it possible to have icons that represent the state, I have linked the issue since if you set icon to `true` in the latest version, then it will display the icon based on state (depending on HA support, for example in my case the icon changes based on whether update is available in zigbee2mqtt).
I have linked the issue since it may solve @i00 problem without templating.
Here is an example how to get a changing light icon in a row:
```yaml
  - entity: light.my_bulb
    name: My Bulb
    secondary_info: last-changed
    show_state: false
    state_color: true
    type: 'custom:multiple-entity-row'
    entities:
      - entity: light.my_bulb
        icon: true
        name: false
        state_color: true
      - entity: binary_sensor.my_bulb_available
        icon: true
        name: false
```
