### ISSUE TITLE
Secondary entity fail in .107

### ISSUE THREAD

**Issue by mycanaletto** [benct/lovelace-multiple-entity-row#62]
Hello,
I have a little problem with the .107:

in .107
![image](https://user-images.githubusercontent.com/45459269/77072862-a3d50100-69ee-11ea-8e1a-3990bb6c2647.png)

in.106
![image](https://user-images.githubusercontent.com/45459269/77072931-bea77580-69ee-11ea-8d17-161e01a1b88c.png)

```
  - entities:
      - entity: binary_sensor.porte_garage
        name: false
      - entity: sensor.porte_garage_battery_level
        name: false
    entity: binary_sensor.porte_garage
    name: 'Porte : Garage'
    secondary_info: sensor.last_open_porte_garage
    show_state: false
    toggle: true
    type: 'custom:multiple-entity-row'
```
The values return are OK
![image](https://user-images.githubusercontent.com/45459269/77073139-134af080-69ef-11ea-9971-b7c64cf8e110.png)

If I use `secondary_info: last-changed` : OK
