### ISSUE TITLE
Colored icons for attributes

### ISSUE THREAD

**Issue by stezak77** [benct/lovelace-multiple-entity-row#68]
I have defined the list of the entities as attributes, each one represented by an icon.

Since they are all binary attributes, I would like each icon colored based on the value of the attribute itself.

Currently, all the icons are colored based on the main entity state.

![image](https://user-images.githubusercontent.com/49878007/79459720-01f80280-7ff4-11ea-91ad-1afbcdad528a.png)

```
  - type: 'custom:multiple-entity-row'
    name: Front Door
    entity: binary_sensor.front_door
    show_state: false
    secondary_info: last-changed
    entities:
      - attribute: alarm
        state_color: true
        icon: 'mdi:bell'
      - attribute: bypass
        state_color: true
        icon: 'mdi:shield-off'
      - attribute: lowbatt
        state_color: true
        icon: 'mdi:battery-alert'
      - attribute: fault
        state_color: true
        icon: 'mdi:alert'
```

Would it be possible?

Here's a mockup of what I'd like to achieve (2nd attribute is ON, all other attributes are OFF):

![image](https://user-images.githubusercontent.com/49878007/79459914-5307f680-7ff4-11ea-8ded-209e16938473.png)

**Comment by stezak77** [comment]
What do you think @benct ?
Any chance to have this feature?

**Comment by drinfernoo** [comment]
Has anyone figured out a way to work around this?

**Comment by stezak77** [comment]
An attribute does not have a type and a device_class, so it's not currently possible to define its state. I think new properties should be added in the configuration for the purpose.

**Comment by drinfernoo** [comment]
Could we perhaps have an option for `state_template`? That would allow us to define a template that, when true, would indicate an "on" state.

**Comment by stezak77** [comment]
That could be an option, although templates are not supported by the card.
Consider the solution with the separate template entity already works now, though defining all the needed template entities might not be very practical (it depends on how many you need)

**Comment by drinfernoo** [comment]
@stezak77 Right.

I already have a REST sensor which queries my Hyperion server, and a template sensor that organizes my needed values into sensor attributes.

I only use six attributes in this way at the moment, which in this instance only means six new switches for my card... but I could easily see a more complex usage of this row leaving my entities cluttered very quickly.

I've done as you suggested, and it does work for my situation, as well as giving me the opportunity to make those icons interactive via a REST command. While this is a somewhat reasonable workaround, it would be very much more convenient to have an actual solution.

Thanks for the help! I've got it working the way I wanted now anyways 😁

**Comment by jpettitt** [comment]
Each entity can be colored independently now. `icon_color` does it unconditionally in 4.8.0, and 4.9.0-beta adds `color`, both templatable:

```yaml
entities:
  - attribute: power_1
    icon: mdi:flash
    icon_color: "{{ 'green' if state_attr(entity, 'power_1') else 'grey' }}"
```

Closing — reopen if the per-attribute case still doesn't work.
