### ISSUE TITLE
HA 109.0 - State is not correct

### ISSUE THREAD

**Issue by holdestmade** [benct/lovelace-multiple-entity-row#73]
With 108.9, using a connectivity entity the state shows _Connected_, with 109.0 is shows _On_.

If I use just a standard entity it correctly shows _Connected_

See below, first entity shows _Connected_ and the 2nd entity shows _On_

```
type: entities
show_header_toggle: false
entities:
  - entity: binary_sensor.pinginternet
    name: Internet

  - entity: binary_sensor.pinginternet
    name: Internet
    type: custom:multiple-entity-row
    secondary_info:
      attribute: round_trip_time_mdev

```
