### ISSUE TITLE
Feature request: Confirmation on toggle

### ISSUE THREAD

**Issue by asg8198** [benct/lovelace-multiple-entity-row#76]
Looking to have the confirmation dialog on a standard toggle button. That is to say when we use toggle: true.

**Comment by benct** [comment]
Not sure this will work as the toggle button has its own click handler, but could you try something like this example?:
```
entity: light.living_room
type: custom:multiple-entity-row
tap_action:
  action: toggle
  confirmation: true
```
