### ISSUE TITLE
Feature Request: Attributes of other entities

### ISSUE THREAD

**Issue by Nornode** [benct/lovelace-multiple-entity-row#83]
As shown below. 
I find it would be useful to adding attributes not only of the "main" entity but also from related entities such as an underlying device tracker to get e.g. battery level & SSID name.

```
type: entities
title: Persons
entities:
  - entity: person.owner
    type: 'custom:multiple-entity-row'
    secondary_info: last-changed
    entities:
      - attribute: device_tracker.mobile-phone.battery-percent
```

Thanks!

**Comment by benct** [comment]
Should be possible already with something like:

```
entities:
  - entity: person.owner
    type: 'custom:multiple-entity-row'
    secondary_info: last-changed
    entities:
      - entity: device_tracker.mobile-phone
        attribute: battery-percent
```
