### ISSUE TITLE
Feature request: name as template

### ISSUE THREAD

**Issue by Nornode** [benct/lovelace-multiple-entity-row#84]
Hi again, 

I'm basically using your card as my default Entities card, it's awesome.
Thank you so much!

Another question/request:
Would it be possible to use the 'name:' with a template?

e.g:
```
entities:
  - entity: device_tracker.oneplus
    icon: 'mdi:phone'
    name: owner
    secondary_info: last-changed
    type: 'custom:multiple-entity-row'
    entities:
      - entity: sensor.oneplus_battery_level
        name:
          value_template: {{ states(sensor.oneplus_battery_state) }}
```

![Screenshot 2020-06-17 at 13 57 15](https://user-images.githubusercontent.com/10966757/84890337-f16f1180-b0a2-11ea-96f8-686ef21c96e2.png)

At this (and other tests) it'll show "[object Object]" but no sane info like "Discharging" or "Charging" as I would wish it to show.

Many thanks again!
