### ISSUE TITLE
Add attributes from other entities in entity list

### ISSUE THREAD

**Issue by rywr** [benct/lovelace-multiple-entity-row#86]
Could it be possible in future to insert an attribute of another entity in entity list?

Example: As entity sensor.waschmaschine_status is used. It serves attributes I can choose in the line.
```
entities:
  - entities:
      - attribute: programPhase # =>attibute of sensor.waschmaschine_status
        name: Phase
      - entity: sensor.waschmaschine_target_temperature_0
        name: Temp.
      - entity: sensor.waschmaschine_remaining_time
        name: Restzeit
    entity: sensor.waschmaschine_status # => Entity with status-list
    icon: 'mdi:washing-machine'
    name: Waschmaschine
    secondary_info:
      entity: sensor.waschmaschine_status 
      name: null
    show_state: false
    state_color: true
    type: 'custom:multiple-entity-row'
```

Problem:
The used entity has no boolean state. It has a state list. The Icon is not highlighted when the washing machine is on.

Trying to solve: Add a new binary sensor (as template-sensor) as entity to get the on/off switched icon color.
```
entities:
  - entities:
      - attribute: programPhase # => not existing as attribute 
        name: Phase
      - entity: sensor.waschmaschine_target_temperature_0
        name: Temp.
      - entity: sensor.waschmaschine_remaining_time
        name: Restzeit
    entity: binary_sensor.waschmaschine_an # => new binary sensor
    icon: 'mdi:washing-machine'
    name: Waschmaschine
    secondary_info:
      entity: sensor.waschmaschine_status
      name: null
    show_state: false
    state_color: true
    type: 'custom:multiple-entity-row'
```

Problem with this arrangement: The attribute is "unknown".
At this position I can add several entities.
But I can't add an attribute of another entity (like attribute of sensor.waschmaschine_status)
For Example:
```
  - entities:
      - entity sensor.waschmaschine_status # => entity
        - attribute: programPhase # => attribute from entity above
          name: Phase
      - entity: sensor.waschmaschine_target_temperature_0
        name: Temp.
    entity: binary_sensor.waschmaschine_an # => new binary sensor
    type: 'custom:multiple-entity-row'
```

Is it possible to extend it?

**Comment by benct** [comment]
This should be supported already, if I understand you correctly, you just have an `-` and indentation too many.. Try something like the following:

```
- entity: binary_sensor.waschmaschine_an
  type: 'custom:multiple-entity-row'
  entities:
    - entity sensor.waschmaschine_status
      attribute: programPhase
      name: Phase
    - entity: sensor.waschmaschine_target_temperature_0
      name: Temp.
```
