### ISSUE TITLE
Documentation update require for Installation instruction

### ISSUE THREAD

**Issue by AbDhops** [benct/lovelace-multiple-entity-row#87]
Installation instruction asks to update in `ui-lovelace.yaml file`.
See below:
`Manually add multiple-entity-row.js to your <config>/www/ folder and add the following to your ui-lovelace.yaml file`

However, due to change in lovelace structure in [Home Assistant](https://www.home-assistant.io/lovelace/dashboards-and-views/), resources has been moved into configuration.yaml
So something like this,
```
lovelace:
  mode: yaml
  # Include external resources only add when mode is yaml, otherwise manage in the resources in the lovelace configuration panel.
  resources:
    - url: /local/my-custom-card.js
      type: module
    - url: /local/my-webfont.css
      type: css
```

This needs to be corrected in installation instruction.
