### ISSUE TITLE
lovelace-multiple-entity-row not working after updating HA to 0.114.4

### ISSUE THREAD

**Issue by skaggake** [benct/lovelace-multiple-entity-row#92]
After updating HA from 0.112.x to 0.114.4 lovelace-multiple-entity-row is not working anymore.
I have installed HACS, installed the multiple-entity-row repository.

Added this rows to configuration.yaml

lovelace:
  mode: yaml
  resources:
  - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module

This configuration has been working perfect to HA version 0.112.
What do i need to change in my configuration?

**Comment by CSnipper** [comment]
Same in my install

**Comment by dadler** [comment]
I have this problem too: the cards stopped working after upgrading from 113.1 to 114.4.  Lovelace now shows:

```
Custom element doesn't exist: multiple-entity-row.

entities:
  - attribute: battery_level
    name: Bat
    unit: '%'
  - attribute: rssi
    name: Sig
entity: binary_sensor.wyzesense_front_door
secondary_info: last-changed
type: 'custom:multiple-entity-row'
```

The error is mentioned in comments on the release notes blog page, but I'm not sure if it's the same cause.

https://community.home-assistant.io/t/0-114-dark-mode-open-z-wave-progress-and-more-automation-scripts/218011/156
