### ISSUE TITLE
Feature request: Header row

### ISSUE THREAD

**Issue by pmazz** [benct/lovelace-multiple-entity-row#93]
Hi Ben,
first of all thanks for your effort in developing the card, I use it broadly in my UI.

What do you think about allowing to define a sort of _header_ row ?

So you could turn something like this:
![image](https://user-images.githubusercontent.com/44721151/92090871-45e77a80-edd0-11ea-9a0b-b21c946cc3d3.png)

Into this (photoshopped):
![image](https://user-images.githubusercontent.com/44721151/92090899-4ed84c00-edd0-11ea-8067-8cac147b8bc7.png)

I tried defining a fake row as first item:
``` yaml
- entity: sensor.fake_sensor
  type: custom:multiple-entity-row
  name: Addons
  icon: []
  show_state: false
  entities:
  - icon: []
  - icon: []
  - icon: []
    name: Installed
  - icon: []
    name: Available
  - icon: []
    name: Status
```

The result is not that much:
![image](https://user-images.githubusercontent.com/44721151/92092067-e12d1f80-edd1-11ea-9e27-8d4832f2db33.png)

Thank you !
