### ISSUE TITLE
secondary_info removes slider from main entity input_number

### ISSUE THREAD

**Issue by Mariusthvdb** [benct/lovelace-multiple-entity-row#96]
trying to have the secondary line below an inout_number with slider to show the state of a another entity using below yaml:
```
      - input_number.front_room_lux
      - type: custom:multiple-entity-row
        entity: input_number.front_room_lux
        secondary_info:
          entity: sensor.front_room_sensor_light_level
          unit: lx
```

shows as:

<img width="420" alt="Schermafbeelding 2020-09-14 om 09 25 12" src="https://user-images.githubusercontent.com/33354141/93056085-37208380-f66c-11ea-8e8d-f4987a3e32a8.png">

As you can see the slider itself is correct (on the single entity line above) but the slider is taken out on the second. Is this a bug, a user error, or a feature ;-)
thanks for having a look.

You can also read this as a FR, to make it possible, if not already...
