### ISSUE TITLE
Support object in attributes

### ISSUE THREAD

**Issue by quammy** [benct/lovelace-multiple-entity-row#97]
Hi, 
First of all - great card! Just started to play with it...
I have a question - how can I set an attribute that is a field in an attribute object?
This is a sample of my object:
```
Time: '2020-09-15T19:26:03'
Epoch: 1600190763
Uptime: '15T04:00:18'
UptimeSec: 1310418
Heap: 27
SleepMode: Dynamic
Sleep: 50
LoadAvg: 19
POWER: 'OFF'
Wifi:
  AP: 1
  SSId: F1
  BSSId: 'B0:4E:26:BD:22:46'
  Channel: 5
  RSSI: 52
  LinkCount: 4
  Downtime: '0T00:01:51'
friendly_name: Switch - Irrigation porch
icon: 'mdi:water'
```
this is the card config:
```
  - entity: switch.sonoff_irrigation_porch
    type: 'custom:multiple-entity-row'
    icon: 'mdi:water'
    name: Irrigation porch
    secondary_info: last-changed
    toggle: true
    state_color: true
    entities:
      - attribute: Wifi.RSSI
        name: RSSI
        unit: dBm
```
and this is the result:
![image](https://user-images.githubusercontent.com/3137488/93244715-d770c800-f792-11ea-9bd0-e587a2ca575c.png)

Thanks!!
